
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345666@tcp(127.0.0.1:3306)/goods"
        descriptionTag: true
    pbentity:
      - link: "mysql:root:12345666@tcp(127.0.0.1:3306)/goods"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app