// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: user_info/v1/user_info.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfoRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" dc:"用户名"`                                         // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" dc:"头像"`                                  // 头像
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                              //
	Sex           int32                  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty" dc:"1男 2女"`                                        // 1男 2女
	Sign          string                 `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty" dc:"个性签名"`                                        // 个性签名
	SecretAnswer  string                 `protobuf:"bytes,6,opt,name=secret_answer,json=secretAnswer,proto3" json:"secret_answer,omitempty" dc:"密保问题的答案"` // 密保问题的答案
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRegisterReq) Reset() {
	*x = UserInfoRegisterReq{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRegisterReq) ProtoMessage() {}

func (x *UserInfoRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRegisterReq.ProtoReflect.Descriptor instead.
func (*UserInfoRegisterReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoRegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfoRegisterReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoRegisterReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfoRegisterReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *UserInfoRegisterReq) GetSecretAnswer() string {
	if x != nil {
		return x.SecretAnswer
	}
	return ""
}

type UserInfoRegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRegisterRes) Reset() {
	*x = UserInfoRegisterRes{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRegisterRes) ProtoMessage() {}

func (x *UserInfoRegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRegisterRes.ProtoReflect.Descriptor instead.
func (*UserInfoRegisterRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoRegisterRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserInfoLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoLoginReq) Reset() {
	*x = UserInfoLoginReq{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoLoginReq) ProtoMessage() {}

func (x *UserInfoLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoLoginReq.ProtoReflect.Descriptor instead.
func (*UserInfoLoginReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfoLoginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserInfoLoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpireIn      uint32                 `protobuf:"varint,3,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"`
	UserInfo      *UserInfoBase          `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoLoginRes) Reset() {
	*x = UserInfoLoginRes{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoLoginRes) ProtoMessage() {}

func (x *UserInfoLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoLoginRes.ProtoReflect.Descriptor instead.
func (*UserInfoLoginRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfoLoginRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserInfoLoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserInfoLoginRes) GetExpireIn() uint32 {
	if x != nil {
		return x.ExpireIn
	}
	return 0
}

func (x *UserInfoLoginRes) GetUserInfo() *UserInfoBase {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfoBase          `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRes) Reset() {
	*x = UserInfoRes{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRes) ProtoMessage() {}

func (x *UserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRes.ProtoReflect.Descriptor instead.
func (*UserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfoRes) GetUserInfo() *UserInfoBase {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInfoUpdatePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SecretAnswer  string                 `protobuf:"bytes,3,opt,name=secret_answer,json=secretAnswer,proto3" json:"secret_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoUpdatePasswordReq) Reset() {
	*x = UserInfoUpdatePasswordReq{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoUpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdatePasswordReq) ProtoMessage() {}

func (x *UserInfoUpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UserInfoUpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoUpdatePasswordReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoUpdatePasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfoUpdatePasswordReq) GetSecretAnswer() string {
	if x != nil {
		return x.SecretAnswer
	}
	return ""
}

type UserInfoUpdatePasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoUpdatePasswordRes) Reset() {
	*x = UserInfoUpdatePasswordRes{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoUpdatePasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdatePasswordRes) ProtoMessage() {}

func (x *UserInfoUpdatePasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdatePasswordRes.ProtoReflect.Descriptor instead.
func (*UserInfoUpdatePasswordRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfoUpdatePasswordRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserInfoBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex           string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Sign          string                 `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	Status        uint32                 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoBase) Reset() {
	*x = UserInfoBase{}
	mi := &file_user_info_v1_user_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoBase) ProtoMessage() {}

func (x *UserInfoBase) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoBase.ProtoReflect.Descriptor instead.
func (*UserInfoBase) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfoBase) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoBase) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoBase) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *UserInfoBase) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *UserInfoBase) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_user_info_v1_user_info_proto protoreflect.FileDescriptor

const file_user_info_v1_user_info_proto_rawDesc = "" +
	"\n" +
	"\x1cuser_info/v1/user_info.proto\x12\tuser_info\"\xa8\x01\n" +
	"\x13UserInfoRegisterReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\x05R\x03sex\x12\x12\n" +
	"\x04sign\x18\x05 \x01(\tR\x04sign\x12#\n" +
	"\rsecret_answer\x18\x06 \x01(\tR\fsecretAnswer\"%\n" +
	"\x13UserInfoRegisterRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"B\n" +
	"\x10UserInfoLoginReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x8f\x01\n" +
	"\x10UserInfoLoginRes\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\texpire_in\x18\x03 \x01(\rR\bexpireIn\x124\n" +
	"\tuser_info\x18\x04 \x01(\v2\x17.user_info.UserInfoBaseR\buserInfo\"\x1d\n" +
	"\vUserInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"C\n" +
	"\vUserInfoRes\x124\n" +
	"\tuser_info\x18\x01 \x01(\v2\x17.user_info.UserInfoBaseR\buserInfo\"l\n" +
	"\x19UserInfoUpdatePasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12#\n" +
	"\rsecret_answer\x18\x03 \x01(\tR\fsecretAnswer\"+\n" +
	"\x19UserInfoUpdatePasswordRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x88\x01\n" +
	"\fUserInfoBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x12\n" +
	"\x04sign\x18\x05 \x01(\tR\x04sign\x12\x16\n" +
	"\x06status\x18\x06 \x01(\rR\x06status2\xbe\x02\n" +
	"\bUserInfo\x12C\n" +
	"\x05Login\x12\x1b.user_info.UserInfoLoginReq\x1a\x1b.user_info.UserInfoLoginRes\"\x00\x12L\n" +
	"\bRegister\x12\x1e.user_info.UserInfoRegisterReq\x1a\x1e.user_info.UserInfoRegisterRes\"\x00\x12^\n" +
	"\x0eUpdatePassword\x12$.user_info.UserInfoUpdatePasswordReq\x1a$.user_info.UserInfoUpdatePasswordRes\"\x00\x12?\n" +
	"\vGetUserInfo\x12\x16.user_info.UserInfoReq\x1a\x16.user_info.UserInfoRes\"\x00B#Z!service/app/user/api/user_info/v1b\x06proto3"

var (
	file_user_info_v1_user_info_proto_rawDescOnce sync.Once
	file_user_info_v1_user_info_proto_rawDescData []byte
)

func file_user_info_v1_user_info_proto_rawDescGZIP() []byte {
	file_user_info_v1_user_info_proto_rawDescOnce.Do(func() {
		file_user_info_v1_user_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_info_v1_user_info_proto_rawDesc), len(file_user_info_v1_user_info_proto_rawDesc)))
	})
	return file_user_info_v1_user_info_proto_rawDescData
}

var file_user_info_v1_user_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_info_v1_user_info_proto_goTypes = []any{
	(*UserInfoRegisterReq)(nil),       // 0: user_info.UserInfoRegisterReq
	(*UserInfoRegisterRes)(nil),       // 1: user_info.UserInfoRegisterRes
	(*UserInfoLoginReq)(nil),          // 2: user_info.UserInfoLoginReq
	(*UserInfoLoginRes)(nil),          // 3: user_info.UserInfoLoginRes
	(*UserInfoReq)(nil),               // 4: user_info.UserInfoReq
	(*UserInfoRes)(nil),               // 5: user_info.UserInfoRes
	(*UserInfoUpdatePasswordReq)(nil), // 6: user_info.UserInfoUpdatePasswordReq
	(*UserInfoUpdatePasswordRes)(nil), // 7: user_info.UserInfoUpdatePasswordRes
	(*UserInfoBase)(nil),              // 8: user_info.UserInfoBase
}
var file_user_info_v1_user_info_proto_depIdxs = []int32{
	8, // 0: user_info.UserInfoLoginRes.user_info:type_name -> user_info.UserInfoBase
	8, // 1: user_info.UserInfoRes.user_info:type_name -> user_info.UserInfoBase
	2, // 2: user_info.UserInfo.Login:input_type -> user_info.UserInfoLoginReq
	0, // 3: user_info.UserInfo.Register:input_type -> user_info.UserInfoRegisterReq
	6, // 4: user_info.UserInfo.UpdatePassword:input_type -> user_info.UserInfoUpdatePasswordReq
	4, // 5: user_info.UserInfo.GetUserInfo:input_type -> user_info.UserInfoReq
	3, // 6: user_info.UserInfo.Login:output_type -> user_info.UserInfoLoginRes
	1, // 7: user_info.UserInfo.Register:output_type -> user_info.UserInfoRegisterRes
	7, // 8: user_info.UserInfo.UpdatePassword:output_type -> user_info.UserInfoUpdatePasswordRes
	5, // 9: user_info.UserInfo.GetUserInfo:output_type -> user_info.UserInfoRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_info_v1_user_info_proto_init() }
func file_user_info_v1_user_info_proto_init() {
	if File_user_info_v1_user_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_info_v1_user_info_proto_rawDesc), len(file_user_info_v1_user_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_info_v1_user_info_proto_goTypes,
		DependencyIndexes: file_user_info_v1_user_info_proto_depIdxs,
		MessageInfos:      file_user_info_v1_user_info_proto_msgTypes,
	}.Build()
	File_user_info_v1_user_info_proto = out.File
	file_user_info_v1_user_info_proto_goTypes = nil
	file_user_info_v1_user_info_proto_depIdxs = nil
}
