// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/order_goods_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderGoodsInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"商品维度的订单表"`                              // 商品维度的订单表
	OrderId        int32                  `protobuf:"varint,2,opt,name=OrderId,proto3" json:"OrderId,omitempty" dc:"关联的主订单表"`                     // 关联的主订单表
	GoodsId        int32                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品id"`                        // 商品id
	GoodsOptionsId int32                  `protobuf:"varint,4,opt,name=GoodsOptionsId,proto3" json:"GoodsOptionsId,omitempty" dc:"商品规格id sku id"` // 商品规格id sku id
	Count          int32                  `protobuf:"varint,5,opt,name=Count,proto3" json:"Count,omitempty" dc:"商品数量"`                            // 商品数量
	Remark         string                 `protobuf:"bytes,6,opt,name=Remark,proto3" json:"Remark,omitempty" dc:"备注"`                             // 备注
	Price          int32                  `protobuf:"varint,7,opt,name=Price,proto3" json:"Price,omitempty" dc:"订单金额 单位分"`                        // 订单金额 单位分
	CouponPrice    int32                  `protobuf:"varint,8,opt,name=CouponPrice,proto3" json:"CouponPrice,omitempty" dc:"优惠券金额 单位分"`           // 优惠券金额 单位分
	ActualPrice    int32                  `protobuf:"varint,9,opt,name=ActualPrice,proto3" json:"ActualPrice,omitempty" dc:"实际支付金额 单位分"`          // 实际支付金额 单位分
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                              //
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                              //
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderGoodsInfo) Reset() {
	*x = OrderGoodsInfo{}
	mi := &file_pbentity_order_goods_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGoodsInfo) ProtoMessage() {}

func (x *OrderGoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_order_goods_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGoodsInfo.ProtoReflect.Descriptor instead.
func (*OrderGoodsInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_order_goods_info_proto_rawDescGZIP(), []int{0}
}

func (x *OrderGoodsInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderGoodsInfo) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderGoodsInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderGoodsInfo) GetGoodsOptionsId() int32 {
	if x != nil {
		return x.GoodsOptionsId
	}
	return 0
}

func (x *OrderGoodsInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderGoodsInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderGoodsInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderGoodsInfo) GetCouponPrice() int32 {
	if x != nil {
		return x.CouponPrice
	}
	return 0
}

func (x *OrderGoodsInfo) GetActualPrice() int32 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

func (x *OrderGoodsInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderGoodsInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pbentity_order_goods_info_proto protoreflect.FileDescriptor

const file_pbentity_order_goods_info_proto_rawDesc = "" +
	"\n" +
	"\x1fpbentity/order_goods_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x02\n" +
	"\x0eOrderGoodsInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x18\n" +
	"\aOrderId\x18\x02 \x01(\x05R\aOrderId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x05R\aGoodsId\x12&\n" +
	"\x0eGoodsOptionsId\x18\x04 \x01(\x05R\x0eGoodsOptionsId\x12\x14\n" +
	"\x05Count\x18\x05 \x01(\x05R\x05Count\x12\x16\n" +
	"\x06Remark\x18\x06 \x01(\tR\x06Remark\x12\x14\n" +
	"\x05Price\x18\a \x01(\x05R\x05Price\x12 \n" +
	"\vCouponPrice\x18\b \x01(\x05R\vCouponPrice\x12 \n" +
	"\vActualPrice\x18\t \x01(\x05R\vActualPrice\x128\n" +
	"\tCreatedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAtB Z\x1eservice/app/order/api/pbentityb\x06proto3"

var (
	file_pbentity_order_goods_info_proto_rawDescOnce sync.Once
	file_pbentity_order_goods_info_proto_rawDescData []byte
)

func file_pbentity_order_goods_info_proto_rawDescGZIP() []byte {
	file_pbentity_order_goods_info_proto_rawDescOnce.Do(func() {
		file_pbentity_order_goods_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_order_goods_info_proto_rawDesc), len(file_pbentity_order_goods_info_proto_rawDesc)))
	})
	return file_pbentity_order_goods_info_proto_rawDescData
}

var file_pbentity_order_goods_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_order_goods_info_proto_goTypes = []any{
	(*OrderGoodsInfo)(nil),        // 0: pbentity.OrderGoodsInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_order_goods_info_proto_depIdxs = []int32{
	1, // 0: pbentity.OrderGoodsInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.OrderGoodsInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_order_goods_info_proto_init() }
func file_pbentity_order_goods_info_proto_init() {
	if File_pbentity_order_goods_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_order_goods_info_proto_rawDesc), len(file_pbentity_order_goods_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_order_goods_info_proto_goTypes,
		DependencyIndexes: file_pbentity_order_goods_info_proto_depIdxs,
		MessageInfos:      file_pbentity_order_goods_info_proto_msgTypes,
	}.Build()
	File_pbentity_order_goods_info_proto = out.File
	file_pbentity_order_goods_info_proto_goTypes = nil
	file_pbentity_order_goods_info_proto_depIdxs = nil
}
