// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/order_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                                   //
	Number           string                 `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty" dc:"订单编号"`                                  // 订单编号
	UserId           int32                  `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`                                 // 用户id
	PayType          int32                  `protobuf:"varint,4,opt,name=PayType,proto3" json:"PayType,omitempty" dc:"支付方式 1微信 2支付宝 3云闪付"`                 // 支付方式 1微信 2支付宝 3云闪付
	Remark           string                 `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark,omitempty" dc:"备注"`                                    // 备注
	PayAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=PayAt,proto3" json:"PayAt,omitempty" dc:"支付时间"`                                    // 支付时间
	Status           int32                  `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty" dc:"订单状态： 1待支付 2已支付待发货 3已发货 4已收货待评价 5已评价"` // 订单状态： 1待支付 2已支付待发货 3已发货 4已收货待评价 5已评价
	ConsigneeName    string                 `protobuf:"bytes,8,opt,name=ConsigneeName,proto3" json:"ConsigneeName,omitempty" dc:"收货人姓名"`                   // 收货人姓名
	ConsigneePhone   string                 `protobuf:"bytes,9,opt,name=ConsigneePhone,proto3" json:"ConsigneePhone,omitempty" dc:"收货人手机号"`                // 收货人手机号
	ConsigneeAddress string                 `protobuf:"bytes,10,opt,name=ConsigneeAddress,proto3" json:"ConsigneeAddress,omitempty" dc:"收货人详细地址"`          // 收货人详细地址
	Price            int32                  `protobuf:"varint,11,opt,name=Price,proto3" json:"Price,omitempty" dc:"订单金额 单位分"`                              // 订单金额 单位分
	CouponPrice      int32                  `protobuf:"varint,12,opt,name=CouponPrice,proto3" json:"CouponPrice,omitempty" dc:"优惠券金额 单位分"`                 // 优惠券金额 单位分
	ActualPrice      int32                  `protobuf:"varint,13,opt,name=ActualPrice,proto3" json:"ActualPrice,omitempty" dc:"实际支付金额 单位分"`                // 实际支付金额 单位分
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                                     //
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                                     //
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_pbentity_order_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_order_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_order_info_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfo) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfo) GetPayType() int32 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *OrderInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderInfo) GetPayAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PayAt
	}
	return nil
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfo) GetConsigneeName() string {
	if x != nil {
		return x.ConsigneeName
	}
	return ""
}

func (x *OrderInfo) GetConsigneePhone() string {
	if x != nil {
		return x.ConsigneePhone
	}
	return ""
}

func (x *OrderInfo) GetConsigneeAddress() string {
	if x != nil {
		return x.ConsigneeAddress
	}
	return ""
}

func (x *OrderInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfo) GetCouponPrice() int32 {
	if x != nil {
		return x.CouponPrice
	}
	return 0
}

func (x *OrderInfo) GetActualPrice() int32 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

func (x *OrderInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pbentity_order_info_proto protoreflect.FileDescriptor

const file_pbentity_order_info_proto_rawDesc = "" +
	"\n" +
	"\x19pbentity/order_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x04\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06Number\x18\x02 \x01(\tR\x06Number\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\x05R\x06UserId\x12\x18\n" +
	"\aPayType\x18\x04 \x01(\x05R\aPayType\x12\x16\n" +
	"\x06Remark\x18\x05 \x01(\tR\x06Remark\x120\n" +
	"\x05PayAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05PayAt\x12\x16\n" +
	"\x06Status\x18\a \x01(\x05R\x06Status\x12$\n" +
	"\rConsigneeName\x18\b \x01(\tR\rConsigneeName\x12&\n" +
	"\x0eConsigneePhone\x18\t \x01(\tR\x0eConsigneePhone\x12*\n" +
	"\x10ConsigneeAddress\x18\n" +
	" \x01(\tR\x10ConsigneeAddress\x12\x14\n" +
	"\x05Price\x18\v \x01(\x05R\x05Price\x12 \n" +
	"\vCouponPrice\x18\f \x01(\x05R\vCouponPrice\x12 \n" +
	"\vActualPrice\x18\r \x01(\x05R\vActualPrice\x128\n" +
	"\tCreatedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAtB Z\x1eservice/app/order/api/pbentityb\x06proto3"

var (
	file_pbentity_order_info_proto_rawDescOnce sync.Once
	file_pbentity_order_info_proto_rawDescData []byte
)

func file_pbentity_order_info_proto_rawDescGZIP() []byte {
	file_pbentity_order_info_proto_rawDescOnce.Do(func() {
		file_pbentity_order_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_order_info_proto_rawDesc), len(file_pbentity_order_info_proto_rawDesc)))
	})
	return file_pbentity_order_info_proto_rawDescData
}

var file_pbentity_order_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_order_info_proto_goTypes = []any{
	(*OrderInfo)(nil),             // 0: pbentity.OrderInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_order_info_proto_depIdxs = []int32{
	1, // 0: pbentity.OrderInfo.PayAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.OrderInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.OrderInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_order_info_proto_init() }
func file_pbentity_order_info_proto_init() {
	if File_pbentity_order_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_order_info_proto_rawDesc), len(file_pbentity_order_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_order_info_proto_goTypes,
		DependencyIndexes: file_pbentity_order_info_proto_depIdxs,
		MessageInfos:      file_pbentity_order_info_proto_msgTypes,
	}.Build()
	File_pbentity_order_info_proto = out.File
	file_pbentity_order_info_proto_goTypes = nil
	file_pbentity_order_info_proto_depIdxs = nil
}
