// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/refund_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefundInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"售后退款表"`                       // 售后退款表
	Number        string                 `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty" dc:"售后订单号"`                // 售后订单号
	OrderId       int32                  `protobuf:"varint,3,opt,name=OrderId,proto3" json:"OrderId,omitempty" dc:"订单id"`              // 订单id
	GoodsId       int32                  `protobuf:"varint,4,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"要售后的商品id"`          // 要售后的商品id
	Reason        string                 `protobuf:"bytes,5,opt,name=Reason,proto3" json:"Reason,omitempty" dc:"退款原因"`                 // 退款原因
	Status        int32                  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态 1待处理 2同意退款 3拒绝退款"` // 状态 1待处理 2同意退款 3拒绝退款
	UserId        int32                  `protobuf:"varint,7,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`                // 用户id
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                     //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                     //
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`                    //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfo) Reset() {
	*x = RefundInfo{}
	mi := &file_pbentity_refund_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfo) ProtoMessage() {}

func (x *RefundInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_refund_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfo.ProtoReflect.Descriptor instead.
func (*RefundInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_refund_info_proto_rawDescGZIP(), []int{0}
}

func (x *RefundInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RefundInfo) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *RefundInfo) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RefundInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *RefundInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RefundInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RefundInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RefundInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RefundInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_refund_info_proto protoreflect.FileDescriptor

const file_pbentity_refund_info_proto_rawDesc = "" +
	"\n" +
	"\x1apbentity/refund_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x02\n" +
	"\n" +
	"RefundInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06Number\x18\x02 \x01(\tR\x06Number\x12\x18\n" +
	"\aOrderId\x18\x03 \x01(\x05R\aOrderId\x12\x18\n" +
	"\aGoodsId\x18\x04 \x01(\x05R\aGoodsId\x12\x16\n" +
	"\x06Reason\x18\x05 \x01(\tR\x06Reason\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\x05R\x06Status\x12\x16\n" +
	"\x06UserId\x18\a \x01(\x05R\x06UserId\x128\n" +
	"\tCreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tDeletedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB Z\x1eservice/app/order/api/pbentityb\x06proto3"

var (
	file_pbentity_refund_info_proto_rawDescOnce sync.Once
	file_pbentity_refund_info_proto_rawDescData []byte
)

func file_pbentity_refund_info_proto_rawDescGZIP() []byte {
	file_pbentity_refund_info_proto_rawDescOnce.Do(func() {
		file_pbentity_refund_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_refund_info_proto_rawDesc), len(file_pbentity_refund_info_proto_rawDesc)))
	})
	return file_pbentity_refund_info_proto_rawDescData
}

var file_pbentity_refund_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_refund_info_proto_goTypes = []any{
	(*RefundInfo)(nil),            // 0: pbentity.RefundInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_refund_info_proto_depIdxs = []int32{
	1, // 0: pbentity.RefundInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.RefundInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.RefundInfo.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_refund_info_proto_init() }
func file_pbentity_refund_info_proto_init() {
	if File_pbentity_refund_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_refund_info_proto_rawDesc), len(file_pbentity_refund_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_refund_info_proto_goTypes,
		DependencyIndexes: file_pbentity_refund_info_proto_depIdxs,
		MessageInfos:      file_pbentity_refund_info_proto_msgTypes,
	}.Build()
	File_pbentity_refund_info_proto = out.File
	file_pbentity_refund_info_proto_goTypes = nil
	file_pbentity_refund_info_proto_depIdxs = nil
}
