// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/consignee_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsigneeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"收货地址表"`                    // 收货地址表
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`                       //
	IsDefault     int32                  `protobuf:"varint,3,opt,name=IsDefault,proto3" json:"IsDefault,omitempty" dc:"默认地址1 非默认0"` // 默认地址1 非默认0
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`                            //
	Phone         string                 `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`                          //
	Province      string                 `protobuf:"bytes,6,opt,name=Province,proto3" json:"Province,omitempty"`                    //
	City          string                 `protobuf:"bytes,7,opt,name=City,proto3" json:"City,omitempty"`                            //
	Town          string                 `protobuf:"bytes,8,opt,name=Town,proto3" json:"Town,omitempty" dc:"县区"`                    // 县区
	Street        string                 `protobuf:"bytes,9,opt,name=Street,proto3" json:"Street,omitempty" dc:"街道乡镇"`              // 街道乡镇
	Detail        string                 `protobuf:"bytes,10,opt,name=Detail,proto3" json:"Detail,omitempty" dc:"地址详情"`             // 地址详情
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                 //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                 //
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`                 //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfo) Reset() {
	*x = ConsigneeInfo{}
	mi := &file_pbentity_consignee_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfo) ProtoMessage() {}

func (x *ConsigneeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_consignee_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfo.ProtoReflect.Descriptor instead.
func (*ConsigneeInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_consignee_info_proto_rawDescGZIP(), []int{0}
}

func (x *ConsigneeInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConsigneeInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConsigneeInfo) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ConsigneeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsigneeInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConsigneeInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ConsigneeInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ConsigneeInfo) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *ConsigneeInfo) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ConsigneeInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ConsigneeInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConsigneeInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConsigneeInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_consignee_info_proto protoreflect.FileDescriptor

const file_pbentity_consignee_info_proto_rawDesc = "" +
	"\n" +
	"\x1dpbentity/consignee_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x03\n" +
	"\rConsigneeInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x1c\n" +
	"\tIsDefault\x18\x03 \x01(\x05R\tIsDefault\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Phone\x18\x05 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bProvince\x18\x06 \x01(\tR\bProvince\x12\x12\n" +
	"\x04City\x18\a \x01(\tR\x04City\x12\x12\n" +
	"\x04Town\x18\b \x01(\tR\x04Town\x12\x16\n" +
	"\x06Street\x18\t \x01(\tR\x06Street\x12\x16\n" +
	"\x06Detail\x18\n" +
	" \x01(\tR\x06Detail\x128\n" +
	"\tCreatedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tDeletedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\x1fZ\x1dservice/app/user/api/pbentityb\x06proto3"

var (
	file_pbentity_consignee_info_proto_rawDescOnce sync.Once
	file_pbentity_consignee_info_proto_rawDescData []byte
)

func file_pbentity_consignee_info_proto_rawDescGZIP() []byte {
	file_pbentity_consignee_info_proto_rawDescOnce.Do(func() {
		file_pbentity_consignee_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_consignee_info_proto_rawDesc), len(file_pbentity_consignee_info_proto_rawDesc)))
	})
	return file_pbentity_consignee_info_proto_rawDescData
}

var file_pbentity_consignee_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_consignee_info_proto_goTypes = []any{
	(*ConsigneeInfo)(nil),         // 0: pbentity.ConsigneeInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_consignee_info_proto_depIdxs = []int32{
	1, // 0: pbentity.ConsigneeInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.ConsigneeInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.ConsigneeInfo.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_consignee_info_proto_init() }
func file_pbentity_consignee_info_proto_init() {
	if File_pbentity_consignee_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_consignee_info_proto_rawDesc), len(file_pbentity_consignee_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_consignee_info_proto_goTypes,
		DependencyIndexes: file_pbentity_consignee_info_proto_depIdxs,
		MessageInfos:      file_pbentity_consignee_info_proto_msgTypes,
	}.Build()
	File_pbentity_consignee_info_proto = out.File
	file_pbentity_consignee_info_proto_goTypes = nil
	file_pbentity_consignee_info_proto_depIdxs = nil
}
