// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/user_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                 //
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" dc:"用户名"`                     // 用户名
	Avatar        string                 `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty" dc:"头像"`                  // 头像
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`                      //
	UserSalt      string                 `protobuf:"bytes,5,opt,name=UserSalt,proto3" json:"UserSalt,omitempty" dc:"加密盐 生成密码用"`       // 加密盐 生成密码用
	Sex           int32                  `protobuf:"varint,6,opt,name=Sex,proto3" json:"Sex,omitempty" dc:"1男 2女"`                    // 1男 2女
	Status        int32                  `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty" dc:"1正常 2拉黑冻结"`          // 1正常 2拉黑冻结
	Sign          string                 `protobuf:"bytes,8,opt,name=Sign,proto3" json:"Sign,omitempty" dc:"个性签名"`                    // 个性签名
	SecretAnswer  string                 `protobuf:"bytes,9,opt,name=SecretAnswer,proto3" json:"SecretAnswer,omitempty" dc:"密保问题的答案"` // 密保问题的答案
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                   //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                   //
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`                   //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pbentity_user_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_user_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_user_info_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfo) GetUserSalt() string {
	if x != nil {
		return x.UserSalt
	}
	return ""
}

func (x *UserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *UserInfo) GetSecretAnswer() string {
	if x != nil {
		return x.SecretAnswer
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_user_info_proto protoreflect.FileDescriptor

const file_pbentity_user_info_proto_rawDesc = "" +
	"\n" +
	"\x18pbentity/user_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x03\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Avatar\x18\x03 \x01(\tR\x06Avatar\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12\x1a\n" +
	"\bUserSalt\x18\x05 \x01(\tR\bUserSalt\x12\x10\n" +
	"\x03Sex\x18\x06 \x01(\x05R\x03Sex\x12\x16\n" +
	"\x06Status\x18\a \x01(\x05R\x06Status\x12\x12\n" +
	"\x04Sign\x18\b \x01(\tR\x04Sign\x12\"\n" +
	"\fSecretAnswer\x18\t \x01(\tR\fSecretAnswer\x128\n" +
	"\tCreatedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tDeletedAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\x1fZ\x1dservice/app/user/api/pbentityb\x06proto3"

var (
	file_pbentity_user_info_proto_rawDescOnce sync.Once
	file_pbentity_user_info_proto_rawDescData []byte
)

func file_pbentity_user_info_proto_rawDescGZIP() []byte {
	file_pbentity_user_info_proto_rawDescOnce.Do(func() {
		file_pbentity_user_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_user_info_proto_rawDesc), len(file_pbentity_user_info_proto_rawDesc)))
	})
	return file_pbentity_user_info_proto_rawDescData
}

var file_pbentity_user_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_user_info_proto_goTypes = []any{
	(*UserInfo)(nil),              // 0: pbentity.UserInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_user_info_proto_depIdxs = []int32{
	1, // 0: pbentity.UserInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.UserInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.UserInfo.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_user_info_proto_init() }
func file_pbentity_user_info_proto_init() {
	if File_pbentity_user_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_user_info_proto_rawDesc), len(file_pbentity_user_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_user_info_proto_goTypes,
		DependencyIndexes: file_pbentity_user_info_proto_depIdxs,
		MessageInfos:      file_pbentity_user_info_proto_msgTypes,
	}.Build()
	File_pbentity_user_info_proto = out.File
	file_pbentity_user_info_proto_goTypes = nil
	file_pbentity_user_info_proto_depIdxs = nil
}
