// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: position_info/v1/position_info.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/banner/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PicUrl        string                 `protobuf:"bytes,1,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
	GoodsName     string                 `protobuf:"bytes,2,opt,name=GoodsName,proto3" json:"GoodsName,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=Link,proto3" json:"Link,omitempty"`
	Sort          uint32                 `protobuf:"varint,4,opt,name=Sort,proto3" json:"Sort,omitempty"`
	GoodsId       uint32                 `protobuf:"varint,5,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoCreateReq) Reset() {
	*x = PositionInfoCreateReq{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoCreateReq) ProtoMessage() {}

func (x *PositionInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoCreateReq.ProtoReflect.Descriptor instead.
func (*PositionInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{0}
}

func (x *PositionInfoCreateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *PositionInfoCreateReq) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *PositionInfoCreateReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PositionInfoCreateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PositionInfoCreateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type PositionInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoCreateRes) Reset() {
	*x = PositionInfoCreateRes{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoCreateRes) ProtoMessage() {}

func (x *PositionInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoCreateRes.ProtoReflect.Descriptor instead.
func (*PositionInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{1}
}

func (x *PositionInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PositionInfoUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PicUrl        string                 `protobuf:"bytes,2,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
	GoodsName     string                 `protobuf:"bytes,3,opt,name=GoodsName,proto3" json:"GoodsName,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=Link,proto3" json:"Link,omitempty"`
	Sort          uint32                 `protobuf:"varint,5,opt,name=Sort,proto3" json:"Sort,omitempty"`
	GoodsId       uint32                 `protobuf:"varint,6,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoUpdateReq) Reset() {
	*x = PositionInfoUpdateReq{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoUpdateReq) ProtoMessage() {}

func (x *PositionInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*PositionInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{2}
}

func (x *PositionInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionInfoUpdateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *PositionInfoUpdateReq) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *PositionInfoUpdateReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PositionInfoUpdateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PositionInfoUpdateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type PositionInfoUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoUpdateRes) Reset() {
	*x = PositionInfoUpdateRes{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoUpdateRes) ProtoMessage() {}

func (x *PositionInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*PositionInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{3}
}

func (x *PositionInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PositionInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoDeleteReq) Reset() {
	*x = PositionInfoDeleteReq{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoDeleteReq) ProtoMessage() {}

func (x *PositionInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*PositionInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{4}
}

func (x *PositionInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PositionInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoDeleteRes) Reset() {
	*x = PositionInfoDeleteRes{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoDeleteRes) ProtoMessage() {}

func (x *PositionInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*PositionInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{5}
}

type PositionInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          uint32                 `protobuf:"varint,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoGetListReq) Reset() {
	*x = PositionInfoGetListReq{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoGetListReq) ProtoMessage() {}

func (x *PositionInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoGetListReq.ProtoReflect.Descriptor instead.
func (*PositionInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{6}
}

func (x *PositionInfoGetListReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PositionInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PositionInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PositionInfoListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	List          []*pbentity.PositionInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoListResponse) Reset() {
	*x = PositionInfoListResponse{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoListResponse) ProtoMessage() {}

func (x *PositionInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoListResponse.ProtoReflect.Descriptor instead.
func (*PositionInfoListResponse) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{7}
}

func (x *PositionInfoListResponse) GetList() []*pbentity.PositionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PositionInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PositionInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PositionInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PositionInfoGetListRes struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *PositionInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfoGetListRes) Reset() {
	*x = PositionInfoGetListRes{}
	mi := &file_position_info_v1_position_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoGetListRes) ProtoMessage() {}

func (x *PositionInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoGetListRes.ProtoReflect.Descriptor instead.
func (*PositionInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{8}
}

func (x *PositionInfoGetListRes) GetData() *PositionInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_position_info_v1_position_info_proto protoreflect.FileDescriptor

const file_position_info_v1_position_info_proto_rawDesc = "" +
	"\n" +
	"$position_info/v1/position_info.proto\x12\x10position_info.v1\x1a\x1cpbentity/position_info.proto\"\x8f\x01\n" +
	"\x15PositionInfoCreateReq\x12\x16\n" +
	"\x06PicUrl\x18\x01 \x01(\tR\x06PicUrl\x12\x1c\n" +
	"\tGoodsName\x18\x02 \x01(\tR\tGoodsName\x12\x12\n" +
	"\x04Link\x18\x03 \x01(\tR\x04Link\x12\x12\n" +
	"\x04Sort\x18\x04 \x01(\rR\x04Sort\x12\x18\n" +
	"\aGoodsId\x18\x05 \x01(\rR\aGoodsId\"'\n" +
	"\x15PositionInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x9f\x01\n" +
	"\x15PositionInfoUpdateReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x16\n" +
	"\x06PicUrl\x18\x02 \x01(\tR\x06PicUrl\x12\x1c\n" +
	"\tGoodsName\x18\x03 \x01(\tR\tGoodsName\x12\x12\n" +
	"\x04Link\x18\x04 \x01(\tR\x04Link\x12\x12\n" +
	"\x04Sort\x18\x05 \x01(\rR\x04Sort\x12\x18\n" +
	"\aGoodsId\x18\x06 \x01(\rR\aGoodsId\"'\n" +
	"\x15PositionInfoUpdateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"'\n" +
	"\x15PositionInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x17\n" +
	"\x15PositionInfoDeleteRes\"T\n" +
	"\x16PositionInfoGetListReq\x12\x12\n" +
	"\x04sort\x18\x01 \x01(\rR\x04sort\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"\x84\x01\n" +
	"\x18PositionInfoListResponse\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.pbentity.PositionInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"X\n" +
	"\x16PositionInfoGetListRes\x12>\n" +
	"\x04data\x18\x01 \x01(\v2*.position_info.v1.PositionInfoListResponseR\x04data2\x8a\x03\n" +
	"\rposition_info\x12_\n" +
	"\aGetList\x12(.position_info.v1.PositionInfoGetListReq\x1a(.position_info.v1.PositionInfoGetListRes\"\x00\x12\\\n" +
	"\x06Create\x12'.position_info.v1.PositionInfoCreateReq\x1a'.position_info.v1.PositionInfoCreateRes\"\x00\x12\\\n" +
	"\x06Update\x12'.position_info.v1.PositionInfoUpdateReq\x1a'.position_info.v1.PositionInfoUpdateRes\"\x00\x12\\\n" +
	"\x06Delete\x12'.position_info.v1.PositionInfoDeleteReq\x1a'.position_info.v1.PositionInfoDeleteRes\"\x00B)Z'service/app/banner/api/position_info/v1b\x06proto3"

var (
	file_position_info_v1_position_info_proto_rawDescOnce sync.Once
	file_position_info_v1_position_info_proto_rawDescData []byte
)

func file_position_info_v1_position_info_proto_rawDescGZIP() []byte {
	file_position_info_v1_position_info_proto_rawDescOnce.Do(func() {
		file_position_info_v1_position_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_position_info_v1_position_info_proto_rawDesc), len(file_position_info_v1_position_info_proto_rawDesc)))
	})
	return file_position_info_v1_position_info_proto_rawDescData
}

var file_position_info_v1_position_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_position_info_v1_position_info_proto_goTypes = []any{
	(*PositionInfoCreateReq)(nil),    // 0: position_info.v1.PositionInfoCreateReq
	(*PositionInfoCreateRes)(nil),    // 1: position_info.v1.PositionInfoCreateRes
	(*PositionInfoUpdateReq)(nil),    // 2: position_info.v1.PositionInfoUpdateReq
	(*PositionInfoUpdateRes)(nil),    // 3: position_info.v1.PositionInfoUpdateRes
	(*PositionInfoDeleteReq)(nil),    // 4: position_info.v1.PositionInfoDeleteReq
	(*PositionInfoDeleteRes)(nil),    // 5: position_info.v1.PositionInfoDeleteRes
	(*PositionInfoGetListReq)(nil),   // 6: position_info.v1.PositionInfoGetListReq
	(*PositionInfoListResponse)(nil), // 7: position_info.v1.PositionInfoListResponse
	(*PositionInfoGetListRes)(nil),   // 8: position_info.v1.PositionInfoGetListRes
	(*pbentity.PositionInfo)(nil),    // 9: pbentity.PositionInfo
}
var file_position_info_v1_position_info_proto_depIdxs = []int32{
	9, // 0: position_info.v1.PositionInfoListResponse.list:type_name -> pbentity.PositionInfo
	7, // 1: position_info.v1.PositionInfoGetListRes.data:type_name -> position_info.v1.PositionInfoListResponse
	6, // 2: position_info.v1.position_info.GetList:input_type -> position_info.v1.PositionInfoGetListReq
	0, // 3: position_info.v1.position_info.Create:input_type -> position_info.v1.PositionInfoCreateReq
	2, // 4: position_info.v1.position_info.Update:input_type -> position_info.v1.PositionInfoUpdateReq
	4, // 5: position_info.v1.position_info.Delete:input_type -> position_info.v1.PositionInfoDeleteReq
	8, // 6: position_info.v1.position_info.GetList:output_type -> position_info.v1.PositionInfoGetListRes
	1, // 7: position_info.v1.position_info.Create:output_type -> position_info.v1.PositionInfoCreateRes
	3, // 8: position_info.v1.position_info.Update:output_type -> position_info.v1.PositionInfoUpdateRes
	5, // 9: position_info.v1.position_info.Delete:output_type -> position_info.v1.PositionInfoDeleteRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_position_info_v1_position_info_proto_init() }
func file_position_info_v1_position_info_proto_init() {
	if File_position_info_v1_position_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_position_info_v1_position_info_proto_rawDesc), len(file_position_info_v1_position_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_position_info_v1_position_info_proto_goTypes,
		DependencyIndexes: file_position_info_v1_position_info_proto_depIdxs,
		MessageInfos:      file_position_info_v1_position_info_proto_msgTypes,
	}.Build()
	File_position_info_v1_position_info_proto = out.File
	file_position_info_v1_position_info_proto_goTypes = nil
	file_position_info_v1_position_info_proto_depIdxs = nil
}
