// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: rotation_info/v1/rotation_info.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/banner/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RotationInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PicUrl        string                 `protobuf:"bytes,1,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=Link,proto3" json:"Link,omitempty"`
	Sort          uint32                 `protobuf:"varint,3,opt,name=Sort,proto3" json:"Sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoCreateReq) Reset() {
	*x = RotationInfoCreateReq{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoCreateReq) ProtoMessage() {}

func (x *RotationInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoCreateReq.ProtoReflect.Descriptor instead.
func (*RotationInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{0}
}

func (x *RotationInfoCreateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *RotationInfoCreateReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RotationInfoCreateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type RotationInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoCreateRes) Reset() {
	*x = RotationInfoCreateRes{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoCreateRes) ProtoMessage() {}

func (x *RotationInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoCreateRes.ProtoReflect.Descriptor instead.
func (*RotationInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{1}
}

func (x *RotationInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RotationInfoUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PicUrl        string                 `protobuf:"bytes,2,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=Link,proto3" json:"Link,omitempty"`
	Sort          uint32                 `protobuf:"varint,4,opt,name=Sort,proto3" json:"Sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoUpdateReq) Reset() {
	*x = RotationInfoUpdateReq{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoUpdateReq) ProtoMessage() {}

func (x *RotationInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*RotationInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{2}
}

func (x *RotationInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RotationInfoUpdateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *RotationInfoUpdateReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RotationInfoUpdateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type RotationInfoUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoUpdateRes) Reset() {
	*x = RotationInfoUpdateRes{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoUpdateRes) ProtoMessage() {}

func (x *RotationInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*RotationInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{3}
}

func (x *RotationInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RotationInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoDeleteReq) Reset() {
	*x = RotationInfoDeleteReq{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoDeleteReq) ProtoMessage() {}

func (x *RotationInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*RotationInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{4}
}

func (x *RotationInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RotationInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoDeleteRes) Reset() {
	*x = RotationInfoDeleteRes{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoDeleteRes) ProtoMessage() {}

func (x *RotationInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*RotationInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{5}
}

type RotationInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          uint32                 `protobuf:"varint,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoGetListReq) Reset() {
	*x = RotationInfoGetListReq{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoGetListReq) ProtoMessage() {}

func (x *RotationInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoGetListReq.ProtoReflect.Descriptor instead.
func (*RotationInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{6}
}

func (x *RotationInfoGetListReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *RotationInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RotationInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RotationInfoListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	List          []*pbentity.RotationInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoListResponse) Reset() {
	*x = RotationInfoListResponse{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoListResponse) ProtoMessage() {}

func (x *RotationInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoListResponse.ProtoReflect.Descriptor instead.
func (*RotationInfoListResponse) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{7}
}

func (x *RotationInfoListResponse) GetList() []*pbentity.RotationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RotationInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RotationInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RotationInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RotationInfoGetListRes struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *RotationInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationInfoGetListRes) Reset() {
	*x = RotationInfoGetListRes{}
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoGetListRes) ProtoMessage() {}

func (x *RotationInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoGetListRes.ProtoReflect.Descriptor instead.
func (*RotationInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{8}
}

func (x *RotationInfoGetListRes) GetData() *RotationInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rotation_info_v1_rotation_info_proto protoreflect.FileDescriptor

const file_rotation_info_v1_rotation_info_proto_rawDesc = "" +
	"\n" +
	"$rotation_info/v1/rotation_info.proto\x12\x10rotation_info.v1\x1a\x1cpbentity/rotation_info.proto\"W\n" +
	"\x15RotationInfoCreateReq\x12\x16\n" +
	"\x06PicUrl\x18\x01 \x01(\tR\x06PicUrl\x12\x12\n" +
	"\x04Link\x18\x02 \x01(\tR\x04Link\x12\x12\n" +
	"\x04Sort\x18\x03 \x01(\rR\x04Sort\"'\n" +
	"\x15RotationInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"g\n" +
	"\x15RotationInfoUpdateReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x16\n" +
	"\x06PicUrl\x18\x02 \x01(\tR\x06PicUrl\x12\x12\n" +
	"\x04Link\x18\x03 \x01(\tR\x04Link\x12\x12\n" +
	"\x04Sort\x18\x04 \x01(\rR\x04Sort\"'\n" +
	"\x15RotationInfoUpdateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"'\n" +
	"\x15RotationInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x17\n" +
	"\x15RotationInfoDeleteRes\"T\n" +
	"\x16RotationInfoGetListReq\x12\x12\n" +
	"\x04sort\x18\x01 \x01(\rR\x04sort\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"\x84\x01\n" +
	"\x18RotationInfoListResponse\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.pbentity.RotationInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"X\n" +
	"\x16RotationInfoGetListRes\x12>\n" +
	"\x04data\x18\x01 \x01(\v2*.rotation_info.v1.RotationInfoListResponseR\x04data2\x8a\x03\n" +
	"\rrotation_info\x12_\n" +
	"\aGetList\x12(.rotation_info.v1.RotationInfoGetListReq\x1a(.rotation_info.v1.RotationInfoGetListRes\"\x00\x12\\\n" +
	"\x06Create\x12'.rotation_info.v1.RotationInfoCreateReq\x1a'.rotation_info.v1.RotationInfoCreateRes\"\x00\x12\\\n" +
	"\x06Update\x12'.rotation_info.v1.RotationInfoUpdateReq\x1a'.rotation_info.v1.RotationInfoUpdateRes\"\x00\x12\\\n" +
	"\x06Delete\x12'.rotation_info.v1.RotationInfoDeleteReq\x1a'.rotation_info.v1.RotationInfoDeleteRes\"\x00B)Z'service/app/banner/api/rotation_info/v1b\x06proto3"

var (
	file_rotation_info_v1_rotation_info_proto_rawDescOnce sync.Once
	file_rotation_info_v1_rotation_info_proto_rawDescData []byte
)

func file_rotation_info_v1_rotation_info_proto_rawDescGZIP() []byte {
	file_rotation_info_v1_rotation_info_proto_rawDescOnce.Do(func() {
		file_rotation_info_v1_rotation_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rotation_info_v1_rotation_info_proto_rawDesc), len(file_rotation_info_v1_rotation_info_proto_rawDesc)))
	})
	return file_rotation_info_v1_rotation_info_proto_rawDescData
}

var file_rotation_info_v1_rotation_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rotation_info_v1_rotation_info_proto_goTypes = []any{
	(*RotationInfoCreateReq)(nil),    // 0: rotation_info.v1.RotationInfoCreateReq
	(*RotationInfoCreateRes)(nil),    // 1: rotation_info.v1.RotationInfoCreateRes
	(*RotationInfoUpdateReq)(nil),    // 2: rotation_info.v1.RotationInfoUpdateReq
	(*RotationInfoUpdateRes)(nil),    // 3: rotation_info.v1.RotationInfoUpdateRes
	(*RotationInfoDeleteReq)(nil),    // 4: rotation_info.v1.RotationInfoDeleteReq
	(*RotationInfoDeleteRes)(nil),    // 5: rotation_info.v1.RotationInfoDeleteRes
	(*RotationInfoGetListReq)(nil),   // 6: rotation_info.v1.RotationInfoGetListReq
	(*RotationInfoListResponse)(nil), // 7: rotation_info.v1.RotationInfoListResponse
	(*RotationInfoGetListRes)(nil),   // 8: rotation_info.v1.RotationInfoGetListRes
	(*pbentity.RotationInfo)(nil),    // 9: pbentity.RotationInfo
}
var file_rotation_info_v1_rotation_info_proto_depIdxs = []int32{
	9, // 0: rotation_info.v1.RotationInfoListResponse.list:type_name -> pbentity.RotationInfo
	7, // 1: rotation_info.v1.RotationInfoGetListRes.data:type_name -> rotation_info.v1.RotationInfoListResponse
	6, // 2: rotation_info.v1.rotation_info.GetList:input_type -> rotation_info.v1.RotationInfoGetListReq
	0, // 3: rotation_info.v1.rotation_info.Create:input_type -> rotation_info.v1.RotationInfoCreateReq
	2, // 4: rotation_info.v1.rotation_info.Update:input_type -> rotation_info.v1.RotationInfoUpdateReq
	4, // 5: rotation_info.v1.rotation_info.Delete:input_type -> rotation_info.v1.RotationInfoDeleteReq
	8, // 6: rotation_info.v1.rotation_info.GetList:output_type -> rotation_info.v1.RotationInfoGetListRes
	1, // 7: rotation_info.v1.rotation_info.Create:output_type -> rotation_info.v1.RotationInfoCreateRes
	3, // 8: rotation_info.v1.rotation_info.Update:output_type -> rotation_info.v1.RotationInfoUpdateRes
	5, // 9: rotation_info.v1.rotation_info.Delete:output_type -> rotation_info.v1.RotationInfoDeleteRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rotation_info_v1_rotation_info_proto_init() }
func file_rotation_info_v1_rotation_info_proto_init() {
	if File_rotation_info_v1_rotation_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rotation_info_v1_rotation_info_proto_rawDesc), len(file_rotation_info_v1_rotation_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rotation_info_v1_rotation_info_proto_goTypes,
		DependencyIndexes: file_rotation_info_v1_rotation_info_proto_depIdxs,
		MessageInfos:      file_rotation_info_v1_rotation_info_proto_msgTypes,
	}.Build()
	File_rotation_info_v1_rotation_info_proto = out.File
	file_rotation_info_v1_rotation_info_proto_goTypes = nil
	file_rotation_info_v1_rotation_info_proto_depIdxs = nil
}
