// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: consignee_info/v1/consignee_info.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/user/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsigneeInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UesrId        uint32                 `protobuf:"varint,1,opt,name=UesrId,proto3" json:"UesrId,omitempty"`
	IsDefault     uint32                 `protobuf:"varint,2,opt,name=IsDefault,proto3" json:"IsDefault,omitempty" dc:"默认地址1 非默认0"` // 默认地址1 非默认0
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                            //
	Phone         string                 `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`                          //
	Province      string                 `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`                    //
	City          string                 `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`                            //
	Town          string                 `protobuf:"bytes,7,opt,name=Town,proto3" json:"Town,omitempty" dc:"县区"`                    // 县区
	Street        string                 `protobuf:"bytes,8,opt,name=Street,proto3" json:"Street,omitempty" dc:"街道乡镇"`              // 街道乡镇
	Detail        string                 `protobuf:"bytes,9,opt,name=Detail,proto3" json:"Detail,omitempty" dc:"地址详情"`              // 地址详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoCreateReq) Reset() {
	*x = ConsigneeInfoCreateReq{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoCreateReq) ProtoMessage() {}

func (x *ConsigneeInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoCreateReq.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{0}
}

func (x *ConsigneeInfoCreateReq) GetUesrId() uint32 {
	if x != nil {
		return x.UesrId
	}
	return 0
}

func (x *ConsigneeInfoCreateReq) GetIsDefault() uint32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ConsigneeInfoCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ConsigneeInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoCreateRes) Reset() {
	*x = ConsigneeInfoCreateRes{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoCreateRes) ProtoMessage() {}

func (x *ConsigneeInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoCreateRes.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{1}
}

func (x *ConsigneeInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConsigneeInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoGetListReq) Reset() {
	*x = ConsigneeInfoGetListReq{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoGetListReq) ProtoMessage() {}

func (x *ConsigneeInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoGetListReq.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{2}
}

func (x *ConsigneeInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ConsigneeInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ConsigneeInfoUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"收货地址表"`                    // 收货地址表
	IsDefault     int32                  `protobuf:"varint,2,opt,name=IsDefault,proto3" json:"IsDefault,omitempty" dc:"默认地址1 非默认0"` // 默认地址1 非默认0
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                            //
	Phone         string                 `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`                          //
	Province      string                 `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`                    //
	City          string                 `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`                            //
	Town          string                 `protobuf:"bytes,7,opt,name=Town,proto3" json:"Town,omitempty" dc:"县区"`                    // 县区
	Street        string                 `protobuf:"bytes,8,opt,name=Street,proto3" json:"Street,omitempty" dc:"街道乡镇"`              // 街道乡镇
	Detail        string                 `protobuf:"bytes,9,opt,name=Detail,proto3" json:"Detail,omitempty" dc:"地址详情"`              // 地址详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoUpdateReq) Reset() {
	*x = ConsigneeInfoUpdateReq{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoUpdateReq) ProtoMessage() {}

func (x *ConsigneeInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{3}
}

func (x *ConsigneeInfoUpdateReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConsigneeInfoUpdateReq) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ConsigneeInfoUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ConsigneeInfoUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoUpdateRes) Reset() {
	*x = ConsigneeInfoUpdateRes{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoUpdateRes) ProtoMessage() {}

func (x *ConsigneeInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{4}
}

func (x *ConsigneeInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConsigneeInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoDeleteReq) Reset() {
	*x = ConsigneeInfoDeleteReq{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoDeleteReq) ProtoMessage() {}

func (x *ConsigneeInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{5}
}

func (x *ConsigneeInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConsigneeInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoDeleteRes) Reset() {
	*x = ConsigneeInfoDeleteRes{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoDeleteRes) ProtoMessage() {}

func (x *ConsigneeInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{6}
}

type ConsigneeInfoGetListResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	List          []*pbentity.ConsigneeInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoGetListResponse) Reset() {
	*x = ConsigneeInfoGetListResponse{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoGetListResponse) ProtoMessage() {}

func (x *ConsigneeInfoGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoGetListResponse.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoGetListResponse) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{7}
}

func (x *ConsigneeInfoGetListResponse) GetList() []*pbentity.ConsigneeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ConsigneeInfoGetListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ConsigneeInfoGetListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ConsigneeInfoGetListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ConsigneeInfoGetListRes struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Data          *ConsigneeInfoGetListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsigneeInfoGetListRes) Reset() {
	*x = ConsigneeInfoGetListRes{}
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsigneeInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoGetListRes) ProtoMessage() {}

func (x *ConsigneeInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_v1_consignee_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoGetListRes.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_consignee_info_v1_consignee_info_proto_rawDescGZIP(), []int{8}
}

func (x *ConsigneeInfoGetListRes) GetData() *ConsigneeInfoGetListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_consignee_info_v1_consignee_info_proto protoreflect.FileDescriptor

const file_consignee_info_v1_consignee_info_proto_rawDesc = "" +
	"\n" +
	"&consignee_info/v1/consignee_info.proto\x12\x0econsignee_info\x1a\x1dpbentity/consignee_info.proto\"\xec\x01\n" +
	"\x16ConsigneeInfoCreateReq\x12\x16\n" +
	"\x06UesrId\x18\x01 \x01(\rR\x06UesrId\x12\x1c\n" +
	"\tIsDefault\x18\x02 \x01(\rR\tIsDefault\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Phone\x18\x04 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bProvince\x18\x05 \x01(\tR\bProvince\x12\x12\n" +
	"\x04City\x18\x06 \x01(\tR\x04City\x12\x12\n" +
	"\x04Town\x18\a \x01(\tR\x04Town\x12\x16\n" +
	"\x06Street\x18\b \x01(\tR\x06Street\x12\x16\n" +
	"\x06Detail\x18\t \x01(\tR\x06Detail\"(\n" +
	"\x16ConsigneeInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"A\n" +
	"\x17ConsigneeInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\xe4\x01\n" +
	"\x16ConsigneeInfoUpdateReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1c\n" +
	"\tIsDefault\x18\x02 \x01(\x05R\tIsDefault\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Phone\x18\x04 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bProvince\x18\x05 \x01(\tR\bProvince\x12\x12\n" +
	"\x04City\x18\x06 \x01(\tR\x04City\x12\x12\n" +
	"\x04Town\x18\a \x01(\tR\x04Town\x12\x16\n" +
	"\x06Street\x18\b \x01(\tR\x06Street\x12\x16\n" +
	"\x06Detail\x18\t \x01(\tR\x06Detail\"(\n" +
	"\x16ConsigneeInfoUpdateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"(\n" +
	"\x16ConsigneeInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x18\n" +
	"\x16ConsigneeInfoDeleteRes\"\x89\x01\n" +
	"\x1cConsigneeInfoGetListResponse\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.pbentity.ConsigneeInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"[\n" +
	"\x17ConsigneeInfoGetListRes\x12@\n" +
	"\x04data\x18\x01 \x01(\v2,.consignee_info.ConsigneeInfoGetListResponseR\x04data2\x83\x03\n" +
	"\x0econsignee_info\x12]\n" +
	"\aGetList\x12'.consignee_info.ConsigneeInfoGetListReq\x1a'.consignee_info.ConsigneeInfoGetListRes\"\x00\x12Z\n" +
	"\x06Create\x12&.consignee_info.ConsigneeInfoCreateReq\x1a&.consignee_info.ConsigneeInfoCreateRes\"\x00\x12Z\n" +
	"\x06Update\x12&.consignee_info.ConsigneeInfoUpdateReq\x1a&.consignee_info.ConsigneeInfoUpdateRes\"\x00\x12Z\n" +
	"\x06Delete\x12&.consignee_info.ConsigneeInfoDeleteReq\x1a&.consignee_info.ConsigneeInfoDeleteRes\"\x00B(Z&service/app/user/api/consignee_info/v1b\x06proto3"

var (
	file_consignee_info_v1_consignee_info_proto_rawDescOnce sync.Once
	file_consignee_info_v1_consignee_info_proto_rawDescData []byte
)

func file_consignee_info_v1_consignee_info_proto_rawDescGZIP() []byte {
	file_consignee_info_v1_consignee_info_proto_rawDescOnce.Do(func() {
		file_consignee_info_v1_consignee_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consignee_info_v1_consignee_info_proto_rawDesc), len(file_consignee_info_v1_consignee_info_proto_rawDesc)))
	})
	return file_consignee_info_v1_consignee_info_proto_rawDescData
}

var file_consignee_info_v1_consignee_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_consignee_info_v1_consignee_info_proto_goTypes = []any{
	(*ConsigneeInfoCreateReq)(nil),       // 0: consignee_info.ConsigneeInfoCreateReq
	(*ConsigneeInfoCreateRes)(nil),       // 1: consignee_info.ConsigneeInfoCreateRes
	(*ConsigneeInfoGetListReq)(nil),      // 2: consignee_info.ConsigneeInfoGetListReq
	(*ConsigneeInfoUpdateReq)(nil),       // 3: consignee_info.ConsigneeInfoUpdateReq
	(*ConsigneeInfoUpdateRes)(nil),       // 4: consignee_info.ConsigneeInfoUpdateRes
	(*ConsigneeInfoDeleteReq)(nil),       // 5: consignee_info.ConsigneeInfoDeleteReq
	(*ConsigneeInfoDeleteRes)(nil),       // 6: consignee_info.ConsigneeInfoDeleteRes
	(*ConsigneeInfoGetListResponse)(nil), // 7: consignee_info.ConsigneeInfoGetListResponse
	(*ConsigneeInfoGetListRes)(nil),      // 8: consignee_info.ConsigneeInfoGetListRes
	(*pbentity.ConsigneeInfo)(nil),       // 9: pbentity.ConsigneeInfo
}
var file_consignee_info_v1_consignee_info_proto_depIdxs = []int32{
	9, // 0: consignee_info.ConsigneeInfoGetListResponse.list:type_name -> pbentity.ConsigneeInfo
	7, // 1: consignee_info.ConsigneeInfoGetListRes.data:type_name -> consignee_info.ConsigneeInfoGetListResponse
	2, // 2: consignee_info.consignee_info.GetList:input_type -> consignee_info.ConsigneeInfoGetListReq
	0, // 3: consignee_info.consignee_info.Create:input_type -> consignee_info.ConsigneeInfoCreateReq
	3, // 4: consignee_info.consignee_info.Update:input_type -> consignee_info.ConsigneeInfoUpdateReq
	5, // 5: consignee_info.consignee_info.Delete:input_type -> consignee_info.ConsigneeInfoDeleteReq
	8, // 6: consignee_info.consignee_info.GetList:output_type -> consignee_info.ConsigneeInfoGetListRes
	1, // 7: consignee_info.consignee_info.Create:output_type -> consignee_info.ConsigneeInfoCreateRes
	4, // 8: consignee_info.consignee_info.Update:output_type -> consignee_info.ConsigneeInfoUpdateRes
	6, // 9: consignee_info.consignee_info.Delete:output_type -> consignee_info.ConsigneeInfoDeleteRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_consignee_info_v1_consignee_info_proto_init() }
func file_consignee_info_v1_consignee_info_proto_init() {
	if File_consignee_info_v1_consignee_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consignee_info_v1_consignee_info_proto_rawDesc), len(file_consignee_info_v1_consignee_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consignee_info_v1_consignee_info_proto_goTypes,
		DependencyIndexes: file_consignee_info_v1_consignee_info_proto_depIdxs,
		MessageInfos:      file_consignee_info_v1_consignee_info_proto_msgTypes,
	}.Build()
	File_consignee_info_v1_consignee_info_proto = out.File
	file_consignee_info_v1_consignee_info_proto_goTypes = nil
	file_consignee_info_v1_consignee_info_proto_depIdxs = nil
}
