// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: comment_info/v1/comment_info.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/interaction/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint32                 `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	ParentId      uint32                 `protobuf:"varint,3,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfoCreateReq) Reset() {
	*x = CommentInfoCreateReq{}
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfoCreateReq) ProtoMessage() {}

func (x *CommentInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfoCreateReq.ProtoReflect.Descriptor instead.
func (*CommentInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_comment_info_v1_comment_info_proto_rawDescGZIP(), []int{0}
}

func (x *CommentInfoCreateReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *CommentInfoCreateReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CommentInfoCreateReq) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentInfoCreateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CommentInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfoCreateRes) Reset() {
	*x = CommentInfoCreateRes{}
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfoCreateRes) ProtoMessage() {}

func (x *CommentInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfoCreateRes.ProtoReflect.Descriptor instead.
func (*CommentInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_comment_info_v1_comment_info_proto_rawDescGZIP(), []int{1}
}

func (x *CommentInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommentInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfoDeleteReq) Reset() {
	*x = CommentInfoDeleteReq{}
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfoDeleteReq) ProtoMessage() {}

func (x *CommentInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*CommentInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_comment_info_v1_comment_info_proto_rawDescGZIP(), []int{2}
}

func (x *CommentInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommentInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfoDeleteRes) Reset() {
	*x = CommentInfoDeleteRes{}
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfoDeleteRes) ProtoMessage() {}

func (x *CommentInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*CommentInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_comment_info_v1_comment_info_proto_rawDescGZIP(), []int{3}
}

func (x *CommentInfoDeleteRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommentInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfoGetListReq) Reset() {
	*x = CommentInfoGetListReq{}
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfoGetListReq) ProtoMessage() {}

func (x *CommentInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfoGetListReq.ProtoReflect.Descriptor instead.
func (*CommentInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_comment_info_v1_comment_info_proto_rawDescGZIP(), []int{4}
}

func (x *CommentInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CommentInfoGetListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	List          []*pbentity.CommentInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfoGetListResponse) Reset() {
	*x = CommentInfoGetListResponse{}
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfoGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfoGetListResponse) ProtoMessage() {}

func (x *CommentInfoGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfoGetListResponse.ProtoReflect.Descriptor instead.
func (*CommentInfoGetListResponse) Descriptor() ([]byte, []int) {
	return file_comment_info_v1_comment_info_proto_rawDescGZIP(), []int{5}
}

func (x *CommentInfoGetListResponse) GetList() []*pbentity.CommentInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CommentInfoGetListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentInfoGetListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CommentInfoGetListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CommentInfoGetListRes struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Data          *CommentInfoGetListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfoGetListRes) Reset() {
	*x = CommentInfoGetListRes{}
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfoGetListRes) ProtoMessage() {}

func (x *CommentInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_comment_info_v1_comment_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfoGetListRes.ProtoReflect.Descriptor instead.
func (*CommentInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_comment_info_v1_comment_info_proto_rawDescGZIP(), []int{6}
}

func (x *CommentInfoGetListRes) GetData() *CommentInfoGetListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_comment_info_v1_comment_info_proto protoreflect.FileDescriptor

const file_comment_info_v1_comment_info_proto_rawDesc = "" +
	"\n" +
	"\"comment_info/v1/comment_info.proto\x12\x0fcomment_info.v1\x1a\x1bpbentity/comment_info.proto\"|\n" +
	"\x14CommentInfoCreateReq\x12\x1a\n" +
	"\bObjectId\x18\x01 \x01(\rR\bObjectId\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\rR\x04Type\x12\x1a\n" +
	"\bParentId\x18\x03 \x01(\rR\bParentId\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\"&\n" +
	"\x14CommentInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"&\n" +
	"\x14CommentInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"&\n" +
	"\x14CommentInfoDeleteRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"?\n" +
	"\x15CommentInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\x85\x01\n" +
	"\x1aCommentInfoGetListResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.pbentity.CommentInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"X\n" +
	"\x15CommentInfoGetListRes\x12?\n" +
	"\x04data\x18\x01 \x01(\v2+.comment_info.v1.CommentInfoGetListResponseR\x04data2\x9f\x02\n" +
	"\fcomment_info\x12[\n" +
	"\aGetList\x12&.comment_info.v1.CommentInfoGetListReq\x1a&.comment_info.v1.CommentInfoGetListRes\"\x00\x12X\n" +
	"\x06Create\x12%.comment_info.v1.CommentInfoCreateReq\x1a%.comment_info.v1.CommentInfoCreateRes\"\x00\x12X\n" +
	"\x06Delete\x12%.comment_info.v1.CommentInfoDeleteReq\x1a%.comment_info.v1.CommentInfoDeleteRes\"\x00B-Z+service/app/interaction/api/comment_info/v1b\x06proto3"

var (
	file_comment_info_v1_comment_info_proto_rawDescOnce sync.Once
	file_comment_info_v1_comment_info_proto_rawDescData []byte
)

func file_comment_info_v1_comment_info_proto_rawDescGZIP() []byte {
	file_comment_info_v1_comment_info_proto_rawDescOnce.Do(func() {
		file_comment_info_v1_comment_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_info_v1_comment_info_proto_rawDesc), len(file_comment_info_v1_comment_info_proto_rawDesc)))
	})
	return file_comment_info_v1_comment_info_proto_rawDescData
}

var file_comment_info_v1_comment_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_comment_info_v1_comment_info_proto_goTypes = []any{
	(*CommentInfoCreateReq)(nil),       // 0: comment_info.v1.CommentInfoCreateReq
	(*CommentInfoCreateRes)(nil),       // 1: comment_info.v1.CommentInfoCreateRes
	(*CommentInfoDeleteReq)(nil),       // 2: comment_info.v1.CommentInfoDeleteReq
	(*CommentInfoDeleteRes)(nil),       // 3: comment_info.v1.CommentInfoDeleteRes
	(*CommentInfoGetListReq)(nil),      // 4: comment_info.v1.CommentInfoGetListReq
	(*CommentInfoGetListResponse)(nil), // 5: comment_info.v1.CommentInfoGetListResponse
	(*CommentInfoGetListRes)(nil),      // 6: comment_info.v1.CommentInfoGetListRes
	(*pbentity.CommentInfo)(nil),       // 7: pbentity.CommentInfo
}
var file_comment_info_v1_comment_info_proto_depIdxs = []int32{
	7, // 0: comment_info.v1.CommentInfoGetListResponse.list:type_name -> pbentity.CommentInfo
	5, // 1: comment_info.v1.CommentInfoGetListRes.data:type_name -> comment_info.v1.CommentInfoGetListResponse
	4, // 2: comment_info.v1.comment_info.GetList:input_type -> comment_info.v1.CommentInfoGetListReq
	0, // 3: comment_info.v1.comment_info.Create:input_type -> comment_info.v1.CommentInfoCreateReq
	2, // 4: comment_info.v1.comment_info.Delete:input_type -> comment_info.v1.CommentInfoDeleteReq
	6, // 5: comment_info.v1.comment_info.GetList:output_type -> comment_info.v1.CommentInfoGetListRes
	1, // 6: comment_info.v1.comment_info.Create:output_type -> comment_info.v1.CommentInfoCreateRes
	3, // 7: comment_info.v1.comment_info.Delete:output_type -> comment_info.v1.CommentInfoDeleteRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_comment_info_v1_comment_info_proto_init() }
func file_comment_info_v1_comment_info_proto_init() {
	if File_comment_info_v1_comment_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_info_v1_comment_info_proto_rawDesc), len(file_comment_info_v1_comment_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_info_v1_comment_info_proto_goTypes,
		DependencyIndexes: file_comment_info_v1_comment_info_proto_depIdxs,
		MessageInfos:      file_comment_info_v1_comment_info_proto_msgTypes,
	}.Build()
	File_comment_info_v1_comment_info_proto = out.File
	file_comment_info_v1_comment_info_proto_goTypes = nil
	file_comment_info_v1_comment_info_proto_depIdxs = nil
}
