// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/praise_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PraiseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"点赞表"`                       // 点赞表
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`                        //
	Type          int32                  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty" dc:"点赞类型 1商品 2文章"`          // 点赞类型 1商品 2文章
	ObjectId      int32                  `protobuf:"varint,4,opt,name=ObjectId,proto3" json:"ObjectId,omitempty" dc:"点赞对象id 方便后期扩展"` // 点赞对象id 方便后期扩展
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                   //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                   //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfo) Reset() {
	*x = PraiseInfo{}
	mi := &file_pbentity_praise_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfo) ProtoMessage() {}

func (x *PraiseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_praise_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfo.ProtoReflect.Descriptor instead.
func (*PraiseInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_praise_info_proto_rawDescGZIP(), []int{0}
}

func (x *PraiseInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PraiseInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PraiseInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PraiseInfo) GetObjectId() int32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *PraiseInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PraiseInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pbentity_praise_info_proto protoreflect.FileDescriptor

const file_pbentity_praise_info_proto_rawDesc = "" +
	"\n" +
	"\x1apbentity/praise_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\n" +
	"PraiseInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\x05R\x04Type\x12\x1a\n" +
	"\bObjectId\x18\x04 \x01(\x05R\bObjectId\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAtB&Z$service/app/interaction/api/pbentityb\x06proto3"

var (
	file_pbentity_praise_info_proto_rawDescOnce sync.Once
	file_pbentity_praise_info_proto_rawDescData []byte
)

func file_pbentity_praise_info_proto_rawDescGZIP() []byte {
	file_pbentity_praise_info_proto_rawDescOnce.Do(func() {
		file_pbentity_praise_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_praise_info_proto_rawDesc), len(file_pbentity_praise_info_proto_rawDesc)))
	})
	return file_pbentity_praise_info_proto_rawDescData
}

var file_pbentity_praise_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_praise_info_proto_goTypes = []any{
	(*PraiseInfo)(nil),            // 0: pbentity.PraiseInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_praise_info_proto_depIdxs = []int32{
	1, // 0: pbentity.PraiseInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.PraiseInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_praise_info_proto_init() }
func file_pbentity_praise_info_proto_init() {
	if File_pbentity_praise_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_praise_info_proto_rawDesc), len(file_pbentity_praise_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_praise_info_proto_goTypes,
		DependencyIndexes: file_pbentity_praise_info_proto_depIdxs,
		MessageInfos:      file_pbentity_praise_info_proto_msgTypes,
	}.Build()
	File_pbentity_praise_info_proto = out.File
	file_pbentity_praise_info_proto_goTypes = nil
	file_pbentity_praise_info_proto_depIdxs = nil
}
