// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/position_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                        //
	PicUrl        string                 `protobuf:"bytes,2,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"图片链接"`       // 图片链接
	GoodsName     string                 `protobuf:"bytes,3,opt,name=GoodsName,proto3" json:"GoodsName,omitempty" dc:"商品名称"` // 商品名称
	Link          string                 `protobuf:"bytes,4,opt,name=Link,proto3" json:"Link,omitempty" dc:"跳转链接"`           // 跳转链接
	Sort          int32                  `protobuf:"varint,5,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"排序"`            // 排序
	GoodsId       int32                  `protobuf:"varint,6,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品id"`    // 商品id
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`           //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`           //
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`           //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfo) Reset() {
	*x = PositionInfo{}
	mi := &file_pbentity_position_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfo) ProtoMessage() {}

func (x *PositionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_position_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfo.ProtoReflect.Descriptor instead.
func (*PositionInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_position_info_proto_rawDescGZIP(), []int{0}
}

func (x *PositionInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionInfo) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *PositionInfo) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *PositionInfo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PositionInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PositionInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *PositionInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PositionInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PositionInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_position_info_proto protoreflect.FileDescriptor

const file_pbentity_position_info_proto_rawDesc = "" +
	"\n" +
	"\x1cpbentity/position_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x02\n" +
	"\fPositionInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06PicUrl\x18\x02 \x01(\tR\x06PicUrl\x12\x1c\n" +
	"\tGoodsName\x18\x03 \x01(\tR\tGoodsName\x12\x12\n" +
	"\x04Link\x18\x04 \x01(\tR\x04Link\x12\x12\n" +
	"\x04Sort\x18\x05 \x01(\x05R\x04Sort\x12\x18\n" +
	"\aGoodsId\x18\x06 \x01(\x05R\aGoodsId\x128\n" +
	"\tCreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tDeletedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB!Z\x1fservice/app/banner/api/pbentityb\x06proto3"

var (
	file_pbentity_position_info_proto_rawDescOnce sync.Once
	file_pbentity_position_info_proto_rawDescData []byte
)

func file_pbentity_position_info_proto_rawDescGZIP() []byte {
	file_pbentity_position_info_proto_rawDescOnce.Do(func() {
		file_pbentity_position_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_position_info_proto_rawDesc), len(file_pbentity_position_info_proto_rawDesc)))
	})
	return file_pbentity_position_info_proto_rawDescData
}

var file_pbentity_position_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_position_info_proto_goTypes = []any{
	(*PositionInfo)(nil),          // 0: pbentity.PositionInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_position_info_proto_depIdxs = []int32{
	1, // 0: pbentity.PositionInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.PositionInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.PositionInfo.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_position_info_proto_init() }
func file_pbentity_position_info_proto_init() {
	if File_pbentity_position_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_position_info_proto_rawDesc), len(file_pbentity_position_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_position_info_proto_goTypes,
		DependencyIndexes: file_pbentity_position_info_proto_depIdxs,
		MessageInfos:      file_pbentity_position_info_proto_msgTypes,
	}.Build()
	File_pbentity_position_info_proto = out.File
	file_pbentity_position_info_proto_goTypes = nil
	file_pbentity_position_info_proto_depIdxs = nil
}
