// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: order_info/v1/order_info.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/order/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderInfoCreateReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Price            uint32                 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	CouponPrice      uint32                 `protobuf:"varint,2,opt,name=coupon_price,json=couponPrice,proto3" json:"coupon_price,omitempty"`
	ActualPrice      uint32                 `protobuf:"varint,3,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty"`
	ConsigneeName    string                 `protobuf:"bytes,4,opt,name=consignee_name,json=consigneeName,proto3" json:"consignee_name,omitempty"`
	ConsigneePhone   string                 `protobuf:"bytes,5,opt,name=consignee_phone,json=consigneePhone,proto3" json:"consignee_phone,omitempty"`
	ConsigneeAddress string                 `protobuf:"bytes,6,opt,name=consignee_address,json=consigneeAddress,proto3" json:"consignee_address,omitempty"`
	Remark           string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	OrderGoodsInfo   []*OrderGoodsItem      `protobuf:"bytes,8,rep,name=order_goods_info,json=orderGoodsInfo,proto3" json:"order_goods_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderInfoCreateReq) Reset() {
	*x = OrderInfoCreateReq{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoCreateReq) ProtoMessage() {}

func (x *OrderInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoCreateReq.ProtoReflect.Descriptor instead.
func (*OrderInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfoCreateReq) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfoCreateReq) GetCouponPrice() uint32 {
	if x != nil {
		return x.CouponPrice
	}
	return 0
}

func (x *OrderInfoCreateReq) GetActualPrice() uint32 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

func (x *OrderInfoCreateReq) GetConsigneeName() string {
	if x != nil {
		return x.ConsigneeName
	}
	return ""
}

func (x *OrderInfoCreateReq) GetConsigneePhone() string {
	if x != nil {
		return x.ConsigneePhone
	}
	return ""
}

func (x *OrderInfoCreateReq) GetConsigneeAddress() string {
	if x != nil {
		return x.ConsigneeAddress
	}
	return ""
}

func (x *OrderInfoCreateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderInfoCreateReq) GetOrderGoodsInfo() []*OrderGoodsItem {
	if x != nil {
		return x.OrderGoodsInfo
	}
	return nil
}

type OrderGoodsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       uint32                 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsOptionId uint32                 `protobuf:"varint,2,opt,name=goods_option_id,json=goodsOptionId,proto3" json:"goods_option_id,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Price         uint32                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CouponPrice   uint32                 `protobuf:"varint,6,opt,name=coupon_price,json=couponPrice,proto3" json:"coupon_price,omitempty"`
	ActualPrice   uint32                 `protobuf:"varint,7,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGoodsItem) Reset() {
	*x = OrderGoodsItem{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGoodsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGoodsItem) ProtoMessage() {}

func (x *OrderGoodsItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGoodsItem.ProtoReflect.Descriptor instead.
func (*OrderGoodsItem) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{1}
}

func (x *OrderGoodsItem) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *OrderGoodsItem) GetGoodsOptionId() uint32 {
	if x != nil {
		return x.GoodsOptionId
	}
	return 0
}

func (x *OrderGoodsItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderGoodsItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderGoodsItem) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderGoodsItem) GetCouponPrice() uint32 {
	if x != nil {
		return x.CouponPrice
	}
	return 0
}

func (x *OrderGoodsItem) GetActualPrice() uint32 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

type OrderInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoCreateRes) Reset() {
	*x = OrderInfoCreateRes{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoCreateRes) ProtoMessage() {}

func (x *OrderInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoCreateRes.ProtoReflect.Descriptor instead.
func (*OrderInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{2}
}

func (x *OrderInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderInfoGetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoGetDetailReq) Reset() {
	*x = OrderInfoGetDetailReq{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoGetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoGetDetailReq) ProtoMessage() {}

func (x *OrderInfoGetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoGetDetailReq.ProtoReflect.Descriptor instead.
func (*OrderInfoGetDetailReq) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{3}
}

func (x *OrderInfoGetDetailReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderInfoGetDetailRes struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	OrderInfo       *pbentity.OrderInfo        `protobuf:"bytes,1,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	OrderGoodsInfos []*pbentity.OrderGoodsInfo `protobuf:"bytes,2,rep,name=order_goods_infos,json=orderGoodsInfos,proto3" json:"order_goods_infos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderInfoGetDetailRes) Reset() {
	*x = OrderInfoGetDetailRes{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoGetDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoGetDetailRes) ProtoMessage() {}

func (x *OrderInfoGetDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoGetDetailRes.ProtoReflect.Descriptor instead.
func (*OrderInfoGetDetailRes) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{4}
}

func (x *OrderInfoGetDetailRes) GetOrderInfo() *pbentity.OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

func (x *OrderInfoGetDetailRes) GetOrderGoodsInfos() []*pbentity.OrderGoodsInfo {
	if x != nil {
		return x.OrderGoodsInfos
	}
	return nil
}

type OrderInfoGetListReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size           uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Number         string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	UserId         uint32                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PayType        uint32                 `protobuf:"varint,5,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	PayAtGte       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=pay_at_gte,json=payAtGte,proto3" json:"pay_at_gte,omitempty"`
	PayAtLte       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=pay_at_lte,json=payAtLte,proto3" json:"pay_at_lte,omitempty"`
	Status         uint32                 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	ConsigneePhone string                 `protobuf:"bytes,9,opt,name=consignee_phone,json=consigneePhone,proto3" json:"consignee_phone,omitempty"`
	PriceGte       uint32                 `protobuf:"varint,10,opt,name=price_gte,json=priceGte,proto3" json:"price_gte,omitempty"`
	PriceLte       uint32                 `protobuf:"varint,11,opt,name=price_lte,json=priceLte,proto3" json:"price_lte,omitempty"`
	DateGte        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=date_gte,json=dateGte,proto3" json:"date_gte,omitempty"`
	DateLte        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_lte,json=dateLte,proto3" json:"date_lte,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderInfoGetListReq) Reset() {
	*x = OrderInfoGetListReq{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoGetListReq) ProtoMessage() {}

func (x *OrderInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoGetListReq.ProtoReflect.Descriptor instead.
func (*OrderInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{5}
}

func (x *OrderInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OrderInfoGetListReq) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderInfoGetListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderInfoGetListReq) GetPayType() uint32 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *OrderInfoGetListReq) GetPayAtGte() *timestamppb.Timestamp {
	if x != nil {
		return x.PayAtGte
	}
	return nil
}

func (x *OrderInfoGetListReq) GetPayAtLte() *timestamppb.Timestamp {
	if x != nil {
		return x.PayAtLte
	}
	return nil
}

func (x *OrderInfoGetListReq) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfoGetListReq) GetConsigneePhone() string {
	if x != nil {
		return x.ConsigneePhone
	}
	return ""
}

func (x *OrderInfoGetListReq) GetPriceGte() uint32 {
	if x != nil {
		return x.PriceGte
	}
	return 0
}

func (x *OrderInfoGetListReq) GetPriceLte() uint32 {
	if x != nil {
		return x.PriceLte
	}
	return 0
}

func (x *OrderInfoGetListReq) GetDateGte() *timestamppb.Timestamp {
	if x != nil {
		return x.DateGte
	}
	return nil
}

func (x *OrderInfoGetListReq) GetDateLte() *timestamppb.Timestamp {
	if x != nil {
		return x.DateLte
	}
	return nil
}

type OrderInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.OrderInfo  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoListResponse) Reset() {
	*x = OrderInfoListResponse{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoListResponse) ProtoMessage() {}

func (x *OrderInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoListResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoListResponse) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{6}
}

func (x *OrderInfoListResponse) GetList() []*pbentity.OrderInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *OrderInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type OrderInfoGetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *OrderInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoGetListRes) Reset() {
	*x = OrderInfoGetListRes{}
	mi := &file_order_info_v1_order_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoGetListRes) ProtoMessage() {}

func (x *OrderInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_info_v1_order_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoGetListRes.ProtoReflect.Descriptor instead.
func (*OrderInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_order_info_v1_order_info_proto_rawDescGZIP(), []int{7}
}

func (x *OrderInfoGetListRes) GetData() *OrderInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_order_info_v1_order_info_proto protoreflect.FileDescriptor

const file_order_info_v1_order_info_proto_rawDesc = "" +
	"\n" +
	"\x1eorder_info/v1/order_info.proto\x12\rorder_info.v1\x1a\x19pbentity/order_info.proto\x1a\x1fpbentity/order_goods_info.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x02\n" +
	"\x12OrderInfoCreateReq\x12\x14\n" +
	"\x05price\x18\x01 \x01(\rR\x05price\x12!\n" +
	"\fcoupon_price\x18\x02 \x01(\rR\vcouponPrice\x12!\n" +
	"\factual_price\x18\x03 \x01(\rR\vactualPrice\x12%\n" +
	"\x0econsignee_name\x18\x04 \x01(\tR\rconsigneeName\x12'\n" +
	"\x0fconsignee_phone\x18\x05 \x01(\tR\x0econsigneePhone\x12+\n" +
	"\x11consignee_address\x18\x06 \x01(\tR\x10consigneeAddress\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12G\n" +
	"\x10order_goods_info\x18\b \x03(\v2\x1d.order_info.v1.OrderGoodsItemR\x0eorderGoodsInfo\"\xdd\x01\n" +
	"\x0eOrderGoodsItem\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\rR\agoodsId\x12&\n" +
	"\x0fgoods_option_id\x18\x02 \x01(\rR\rgoodsOptionId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x14\n" +
	"\x05price\x18\x05 \x01(\rR\x05price\x12!\n" +
	"\fcoupon_price\x18\x06 \x01(\rR\vcouponPrice\x12!\n" +
	"\factual_price\x18\a \x01(\rR\vactualPrice\"$\n" +
	"\x12OrderInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"'\n" +
	"\x15OrderInfoGetDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x91\x01\n" +
	"\x15OrderInfoGetDetailRes\x122\n" +
	"\n" +
	"order_info\x18\x01 \x01(\v2\x13.pbentity.OrderInfoR\torderInfo\x12D\n" +
	"\x11order_goods_infos\x18\x02 \x03(\v2\x18.pbentity.OrderGoodsInfoR\x0forderGoodsInfos\"\xe6\x03\n" +
	"\x13OrderInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\rR\x06userId\x12\x19\n" +
	"\bpay_type\x18\x05 \x01(\rR\apayType\x128\n" +
	"\n" +
	"pay_at_gte\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bpayAtGte\x128\n" +
	"\n" +
	"pay_at_lte\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bpayAtLte\x12\x16\n" +
	"\x06status\x18\b \x01(\rR\x06status\x12'\n" +
	"\x0fconsignee_phone\x18\t \x01(\tR\x0econsigneePhone\x12\x1b\n" +
	"\tprice_gte\x18\n" +
	" \x01(\rR\bpriceGte\x12\x1b\n" +
	"\tprice_lte\x18\v \x01(\rR\bpriceLte\x125\n" +
	"\bdate_gte\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\adateGte\x125\n" +
	"\bdate_lte\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\adateLte\"~\n" +
	"\x15OrderInfoListResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.pbentity.OrderInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"O\n" +
	"\x13OrderInfoGetListRes\x128\n" +
	"\x04data\x18\x01 \x01(\v2$.order_info.v1.OrderInfoListResponseR\x04data2\x8e\x02\n" +
	"\n" +
	"order_info\x12P\n" +
	"\x06Create\x12!.order_info.v1.OrderInfoCreateReq\x1a!.order_info.v1.OrderInfoCreateRes\"\x00\x12Y\n" +
	"\tGetDetail\x12$.order_info.v1.OrderInfoGetDetailReq\x1a$.order_info.v1.OrderInfoGetDetailRes\"\x00\x12S\n" +
	"\aGetList\x12\".order_info.v1.OrderInfoGetListReq\x1a\".order_info.v1.OrderInfoGetListRes\"\x00B%Z#service/app/order/api/order_info/v1b\x06proto3"

var (
	file_order_info_v1_order_info_proto_rawDescOnce sync.Once
	file_order_info_v1_order_info_proto_rawDescData []byte
)

func file_order_info_v1_order_info_proto_rawDescGZIP() []byte {
	file_order_info_v1_order_info_proto_rawDescOnce.Do(func() {
		file_order_info_v1_order_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_info_v1_order_info_proto_rawDesc), len(file_order_info_v1_order_info_proto_rawDesc)))
	})
	return file_order_info_v1_order_info_proto_rawDescData
}

var file_order_info_v1_order_info_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_order_info_v1_order_info_proto_goTypes = []any{
	(*OrderInfoCreateReq)(nil),      // 0: order_info.v1.OrderInfoCreateReq
	(*OrderGoodsItem)(nil),          // 1: order_info.v1.OrderGoodsItem
	(*OrderInfoCreateRes)(nil),      // 2: order_info.v1.OrderInfoCreateRes
	(*OrderInfoGetDetailReq)(nil),   // 3: order_info.v1.OrderInfoGetDetailReq
	(*OrderInfoGetDetailRes)(nil),   // 4: order_info.v1.OrderInfoGetDetailRes
	(*OrderInfoGetListReq)(nil),     // 5: order_info.v1.OrderInfoGetListReq
	(*OrderInfoListResponse)(nil),   // 6: order_info.v1.OrderInfoListResponse
	(*OrderInfoGetListRes)(nil),     // 7: order_info.v1.OrderInfoGetListRes
	(*pbentity.OrderInfo)(nil),      // 8: pbentity.OrderInfo
	(*pbentity.OrderGoodsInfo)(nil), // 9: pbentity.OrderGoodsInfo
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_order_info_v1_order_info_proto_depIdxs = []int32{
	1,  // 0: order_info.v1.OrderInfoCreateReq.order_goods_info:type_name -> order_info.v1.OrderGoodsItem
	8,  // 1: order_info.v1.OrderInfoGetDetailRes.order_info:type_name -> pbentity.OrderInfo
	9,  // 2: order_info.v1.OrderInfoGetDetailRes.order_goods_infos:type_name -> pbentity.OrderGoodsInfo
	10, // 3: order_info.v1.OrderInfoGetListReq.pay_at_gte:type_name -> google.protobuf.Timestamp
	10, // 4: order_info.v1.OrderInfoGetListReq.pay_at_lte:type_name -> google.protobuf.Timestamp
	10, // 5: order_info.v1.OrderInfoGetListReq.date_gte:type_name -> google.protobuf.Timestamp
	10, // 6: order_info.v1.OrderInfoGetListReq.date_lte:type_name -> google.protobuf.Timestamp
	8,  // 7: order_info.v1.OrderInfoListResponse.list:type_name -> pbentity.OrderInfo
	6,  // 8: order_info.v1.OrderInfoGetListRes.data:type_name -> order_info.v1.OrderInfoListResponse
	0,  // 9: order_info.v1.order_info.Create:input_type -> order_info.v1.OrderInfoCreateReq
	3,  // 10: order_info.v1.order_info.GetDetail:input_type -> order_info.v1.OrderInfoGetDetailReq
	5,  // 11: order_info.v1.order_info.GetList:input_type -> order_info.v1.OrderInfoGetListReq
	2,  // 12: order_info.v1.order_info.Create:output_type -> order_info.v1.OrderInfoCreateRes
	4,  // 13: order_info.v1.order_info.GetDetail:output_type -> order_info.v1.OrderInfoGetDetailRes
	7,  // 14: order_info.v1.order_info.GetList:output_type -> order_info.v1.OrderInfoGetListRes
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_order_info_v1_order_info_proto_init() }
func file_order_info_v1_order_info_proto_init() {
	if File_order_info_v1_order_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_info_v1_order_info_proto_rawDesc), len(file_order_info_v1_order_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_info_v1_order_info_proto_goTypes,
		DependencyIndexes: file_order_info_v1_order_info_proto_depIdxs,
		MessageInfos:      file_order_info_v1_order_info_proto_msgTypes,
	}.Build()
	File_order_info_v1_order_info_proto = out.File
	file_order_info_v1_order_info_proto_goTypes = nil
	file_order_info_v1_order_info_proto_depIdxs = nil
}
