// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: order_info/v1/order_info.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderInfo_Create_FullMethodName    = "/order_info.v1.order_info/Create"
	OrderInfo_GetDetail_FullMethodName = "/order_info.v1.order_info/GetDetail"
	OrderInfo_GetList_FullMethodName   = "/order_info.v1.order_info/GetList"
)

// OrderInfoClient is the client API for OrderInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderInfoClient interface {
	Create(ctx context.Context, in *OrderInfoCreateReq, opts ...grpc.CallOption) (*OrderInfoCreateRes, error)
	GetDetail(ctx context.Context, in *OrderInfoGetDetailReq, opts ...grpc.CallOption) (*OrderInfoGetDetailRes, error)
	GetList(ctx context.Context, in *OrderInfoGetListReq, opts ...grpc.CallOption) (*OrderInfoGetListRes, error)
}

type orderInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderInfoClient(cc grpc.ClientConnInterface) OrderInfoClient {
	return &orderInfoClient{cc}
}

func (c *orderInfoClient) Create(ctx context.Context, in *OrderInfoCreateReq, opts ...grpc.CallOption) (*OrderInfoCreateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoCreateRes)
	err := c.cc.Invoke(ctx, OrderInfo_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) GetDetail(ctx context.Context, in *OrderInfoGetDetailReq, opts ...grpc.CallOption) (*OrderInfoGetDetailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoGetDetailRes)
	err := c.cc.Invoke(ctx, OrderInfo_GetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderInfoClient) GetList(ctx context.Context, in *OrderInfoGetListReq, opts ...grpc.CallOption) (*OrderInfoGetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfoGetListRes)
	err := c.cc.Invoke(ctx, OrderInfo_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderInfoServer is the server API for OrderInfo service.
// All implementations must embed UnimplementedOrderInfoServer
// for forward compatibility.
type OrderInfoServer interface {
	Create(context.Context, *OrderInfoCreateReq) (*OrderInfoCreateRes, error)
	GetDetail(context.Context, *OrderInfoGetDetailReq) (*OrderInfoGetDetailRes, error)
	GetList(context.Context, *OrderInfoGetListReq) (*OrderInfoGetListRes, error)
	mustEmbedUnimplementedOrderInfoServer()
}

// UnimplementedOrderInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderInfoServer struct{}

func (UnimplementedOrderInfoServer) Create(context.Context, *OrderInfoCreateReq) (*OrderInfoCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOrderInfoServer) GetDetail(context.Context, *OrderInfoGetDetailReq) (*OrderInfoGetDetailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedOrderInfoServer) GetList(context.Context, *OrderInfoGetListReq) (*OrderInfoGetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedOrderInfoServer) mustEmbedUnimplementedOrderInfoServer() {}
func (UnimplementedOrderInfoServer) testEmbeddedByValue()                   {}

// UnsafeOrderInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderInfoServer will
// result in compilation errors.
type UnsafeOrderInfoServer interface {
	mustEmbedUnimplementedOrderInfoServer()
}

func RegisterOrderInfoServer(s grpc.ServiceRegistrar, srv OrderInfoServer) {
	// If the following call pancis, it indicates UnimplementedOrderInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderInfo_ServiceDesc, srv)
}

func _OrderInfo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).Create(ctx, req.(*OrderInfoCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoGetDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).GetDetail(ctx, req.(*OrderInfoGetDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderInfo_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfoGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInfoServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInfo_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInfoServer).GetList(ctx, req.(*OrderInfoGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderInfo_ServiceDesc is the grpc.ServiceDesc for OrderInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_info.v1.order_info",
	HandlerType: (*OrderInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderInfo_Create_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _OrderInfo_GetDetail_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _OrderInfo_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_info/v1/order_info.proto",
}
