// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/permission_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`              //
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" dc:"权限名称"` // 权限名称
	Path          string                 `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty" dc:"路径"`   // 路径
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"` //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"` //
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionInfo) Reset() {
	*x = PermissionInfo{}
	mi := &file_pbentity_permission_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfo) ProtoMessage() {}

func (x *PermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_permission_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfo.ProtoReflect.Descriptor instead.
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_permission_info_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PermissionInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PermissionInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PermissionInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_permission_info_proto protoreflect.FileDescriptor

const file_pbentity_permission_info_proto_rawDesc = "" +
	"\n" +
	"\x1epbentity/permission_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\x0ePermissionInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Path\x18\x03 \x01(\tR\x04Path\x128\n" +
	"\tCreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tDeletedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB Z\x1eservice/app/admin/api/pbentityb\x06proto3"

var (
	file_pbentity_permission_info_proto_rawDescOnce sync.Once
	file_pbentity_permission_info_proto_rawDescData []byte
)

func file_pbentity_permission_info_proto_rawDescGZIP() []byte {
	file_pbentity_permission_info_proto_rawDescOnce.Do(func() {
		file_pbentity_permission_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_permission_info_proto_rawDesc), len(file_pbentity_permission_info_proto_rawDesc)))
	})
	return file_pbentity_permission_info_proto_rawDescData
}

var file_pbentity_permission_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_permission_info_proto_goTypes = []any{
	(*PermissionInfo)(nil),        // 0: pbentity.PermissionInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_permission_info_proto_depIdxs = []int32{
	1, // 0: pbentity.PermissionInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.PermissionInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.PermissionInfo.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_permission_info_proto_init() }
func file_pbentity_permission_info_proto_init() {
	if File_pbentity_permission_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_permission_info_proto_rawDesc), len(file_pbentity_permission_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_permission_info_proto_goTypes,
		DependencyIndexes: file_pbentity_permission_info_proto_depIdxs,
		MessageInfos:      file_pbentity_permission_info_proto_msgTypes,
	}.Build()
	File_pbentity_permission_info_proto = out.File
	file_pbentity_permission_info_proto_goTypes = nil
	file_pbentity_permission_info_proto_depIdxs = nil
}
