// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/role_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`              //
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" dc:"角色名称"` // 角色名称
	Desc          string                 `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty" dc:"描述"`   // 描述
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"` //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"` //
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_pbentity_role_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_role_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_role_info_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *RoleInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoleInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RoleInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_role_info_proto protoreflect.FileDescriptor

const file_pbentity_role_info_proto_rawDesc = "" +
	"\n" +
	"\x18pbentity/role_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Desc\x18\x03 \x01(\tR\x04Desc\x128\n" +
	"\tCreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tDeletedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB Z\x1eservice/app/admin/api/pbentityb\x06proto3"

var (
	file_pbentity_role_info_proto_rawDescOnce sync.Once
	file_pbentity_role_info_proto_rawDescData []byte
)

func file_pbentity_role_info_proto_rawDescGZIP() []byte {
	file_pbentity_role_info_proto_rawDescOnce.Do(func() {
		file_pbentity_role_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_role_info_proto_rawDesc), len(file_pbentity_role_info_proto_rawDesc)))
	})
	return file_pbentity_role_info_proto_rawDescData
}

var file_pbentity_role_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_role_info_proto_goTypes = []any{
	(*RoleInfo)(nil),              // 0: pbentity.RoleInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_role_info_proto_depIdxs = []int32{
	1, // 0: pbentity.RoleInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.RoleInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.RoleInfo.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_role_info_proto_init() }
func file_pbentity_role_info_proto_init() {
	if File_pbentity_role_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_role_info_proto_rawDesc), len(file_pbentity_role_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_role_info_proto_goTypes,
		DependencyIndexes: file_pbentity_role_info_proto_depIdxs,
		MessageInfos:      file_pbentity_role_info_proto_msgTypes,
	}.Build()
	File_pbentity_role_info_proto = out.File
	file_pbentity_role_info_proto_goTypes = nil
	file_pbentity_role_info_proto_depIdxs = nil
}
