// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: goods_info/v1/goods_info.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsInfoGetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoGetDetailReq) Reset() {
	*x = GoodsInfoGetDetailReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoGetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetDetailReq) ProtoMessage() {}

func (x *GoodsInfoGetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetDetailReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetDetailReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsInfoGetDetailReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoGetDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *pbentity.GoodsInfo    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoGetDetailRes) Reset() {
	*x = GoodsInfoGetDetailRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoGetDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetDetailRes) ProtoMessage() {}

func (x *GoodsInfoGetDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetDetailRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetDetailRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsInfoGetDetailRes) GetData() *pbentity.GoodsInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GoodsInfoCreateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price          uint64                 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Level1Category uint32                 `protobuf:"varint,3,opt,name=level1_category,json=level1Category,proto3" json:"level1_category,omitempty"`
	Level2Category uint32                 `protobuf:"varint,4,opt,name=level2_category,json=level2Category,proto3" json:"level2_category,omitempty"`
	Level3Category uint32                 `protobuf:"varint,5,opt,name=level3_category,json=level3Category,proto3" json:"level3_category,omitempty"`
	Brand          string                 `protobuf:"bytes,6,opt,name=brand,proto3" json:"brand,omitempty"`
	Stock          uint32                 `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Sale           uint32                 `protobuf:"varint,8,opt,name=sale,proto3" json:"sale,omitempty"`
	Tags           string                 `protobuf:"bytes,9,opt,name=tags,proto3" json:"tags,omitempty"`
	DetailInfo     string                 `protobuf:"bytes,10,opt,name=detail_info,json=detailInfo,proto3" json:"detail_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GoodsInfoCreateReq) Reset() {
	*x = GoodsInfoCreateReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoCreateReq) ProtoMessage() {}

func (x *GoodsInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoCreateReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsInfoCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetLevel1Category() uint32 {
	if x != nil {
		return x.Level1Category
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetLevel2Category() uint32 {
	if x != nil {
		return x.Level2Category
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetLevel3Category() uint32 {
	if x != nil {
		return x.Level3Category
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetSale() uint32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetDetailInfo() string {
	if x != nil {
		return x.DetailInfo
	}
	return ""
}

type GoodsInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoCreateRes) Reset() {
	*x = GoodsInfoCreateRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoCreateRes) ProtoMessage() {}

func (x *GoodsInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoCreateRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{3}
}

func (x *GoodsInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoUpdateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price          uint64                 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Level1Category uint32                 `protobuf:"varint,4,opt,name=level1_category,json=level1Category,proto3" json:"level1_category,omitempty"`
	Level2Category uint32                 `protobuf:"varint,5,opt,name=level2_category,json=level2Category,proto3" json:"level2_category,omitempty"`
	Level3Category uint32                 `protobuf:"varint,6,opt,name=level3_category,json=level3Category,proto3" json:"level3_category,omitempty"`
	Brand          string                 `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand,omitempty"`
	Stock          uint32                 `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	Sale           uint32                 `protobuf:"varint,9,opt,name=sale,proto3" json:"sale,omitempty"`
	Tags           string                 `protobuf:"bytes,10,opt,name=tags,proto3" json:"tags,omitempty"`
	DetailInfo     string                 `protobuf:"bytes,11,opt,name=detail_info,json=detailInfo,proto3" json:"detail_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GoodsInfoUpdateReq) Reset() {
	*x = GoodsInfoUpdateReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoUpdateReq) ProtoMessage() {}

func (x *GoodsInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetLevel1Category() uint32 {
	if x != nil {
		return x.Level1Category
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetLevel2Category() uint32 {
	if x != nil {
		return x.Level2Category
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetLevel3Category() uint32 {
	if x != nil {
		return x.Level3Category
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetSale() uint32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetDetailInfo() string {
	if x != nil {
		return x.DetailInfo
	}
	return ""
}

type GoodsInfoUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoUpdateRes) Reset() {
	*x = GoodsInfoUpdateRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoUpdateRes) ProtoMessage() {}

func (x *GoodsInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoDeleteReq) Reset() {
	*x = GoodsInfoDeleteReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoDeleteReq) ProtoMessage() {}

func (x *GoodsInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoDeleteRes) Reset() {
	*x = GoodsInfoDeleteRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoDeleteRes) ProtoMessage() {}

func (x *GoodsInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{7}
}

type GoodsInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoGetListReq) Reset() {
	*x = GoodsInfoGetListReq{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetListReq) ProtoMessage() {}

func (x *GoodsInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetListReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{8}
}

func (x *GoodsInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GoodsInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.GoodsInfo  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoListResponse) Reset() {
	*x = GoodsInfoListResponse{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoListResponse) ProtoMessage() {}

func (x *GoodsInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoListResponse.ProtoReflect.Descriptor instead.
func (*GoodsInfoListResponse) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{9}
}

func (x *GoodsInfoListResponse) GetList() []*pbentity.GoodsInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GoodsInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GoodsInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GoodsInfoGetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *GoodsInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoGetListRes) Reset() {
	*x = GoodsInfoGetListRes{}
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetListRes) ProtoMessage() {}

func (x *GoodsInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetListRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{10}
}

func (x *GoodsInfoGetListRes) GetData() *GoodsInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_goods_info_v1_goods_info_proto protoreflect.FileDescriptor

const file_goods_info_v1_goods_info_proto_rawDesc = "" +
	"\n" +
	"\x1egoods_info/v1/goods_info.proto\x12\rgoods_info.v1\x1a\x19pbentity/goods_info.proto\"'\n" +
	"\x15GoodsInfoGetDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"@\n" +
	"\x15GoodsInfoGetDetailRes\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.pbentity.GoodsInfoR\x04data\"\xae\x02\n" +
	"\x12GoodsInfoCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x04R\x05price\x12'\n" +
	"\x0flevel1_category\x18\x03 \x01(\rR\x0elevel1Category\x12'\n" +
	"\x0flevel2_category\x18\x04 \x01(\rR\x0elevel2Category\x12'\n" +
	"\x0flevel3_category\x18\x05 \x01(\rR\x0elevel3Category\x12\x14\n" +
	"\x05brand\x18\x06 \x01(\tR\x05brand\x12\x14\n" +
	"\x05stock\x18\a \x01(\rR\x05stock\x12\x12\n" +
	"\x04sale\x18\b \x01(\rR\x04sale\x12\x12\n" +
	"\x04tags\x18\t \x01(\tR\x04tags\x12\x1f\n" +
	"\vdetail_info\x18\n" +
	" \x01(\tR\n" +
	"detailInfo\"$\n" +
	"\x12GoodsInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xbe\x02\n" +
	"\x12GoodsInfoUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\x12'\n" +
	"\x0flevel1_category\x18\x04 \x01(\rR\x0elevel1Category\x12'\n" +
	"\x0flevel2_category\x18\x05 \x01(\rR\x0elevel2Category\x12'\n" +
	"\x0flevel3_category\x18\x06 \x01(\rR\x0elevel3Category\x12\x14\n" +
	"\x05brand\x18\a \x01(\tR\x05brand\x12\x14\n" +
	"\x05stock\x18\b \x01(\rR\x05stock\x12\x12\n" +
	"\x04sale\x18\t \x01(\rR\x04sale\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x01(\tR\x04tags\x12\x1f\n" +
	"\vdetail_info\x18\v \x01(\tR\n" +
	"detailInfo\"$\n" +
	"\x12GoodsInfoUpdateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"$\n" +
	"\x12GoodsInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x14\n" +
	"\x12GoodsInfoDeleteRes\"=\n" +
	"\x13GoodsInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"~\n" +
	"\x15GoodsInfoListResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.pbentity.GoodsInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"O\n" +
	"\x13GoodsInfoGetListRes\x128\n" +
	"\x04data\x18\x01 \x01(\v2$.goods_info.v1.GoodsInfoListResponseR\x04data2\xb2\x03\n" +
	"\n" +
	"goods_info\x12S\n" +
	"\aGetList\x12\".goods_info.v1.GoodsInfoGetListReq\x1a\".goods_info.v1.GoodsInfoGetListRes\"\x00\x12Y\n" +
	"\tGetDetail\x12$.goods_info.v1.GoodsInfoGetDetailReq\x1a$.goods_info.v1.GoodsInfoGetDetailRes\"\x00\x12P\n" +
	"\x06Create\x12!.goods_info.v1.GoodsInfoCreateReq\x1a!.goods_info.v1.GoodsInfoCreateRes\"\x00\x12P\n" +
	"\x06Update\x12!.goods_info.v1.GoodsInfoUpdateReq\x1a!.goods_info.v1.GoodsInfoUpdateRes\"\x00\x12P\n" +
	"\x06Delete\x12!.goods_info.v1.GoodsInfoDeleteReq\x1a!.goods_info.v1.GoodsInfoDeleteRes\"\x00B%Z#service/app/goods/api/goods_info/v1b\x06proto3"

var (
	file_goods_info_v1_goods_info_proto_rawDescOnce sync.Once
	file_goods_info_v1_goods_info_proto_rawDescData []byte
)

func file_goods_info_v1_goods_info_proto_rawDescGZIP() []byte {
	file_goods_info_v1_goods_info_proto_rawDescOnce.Do(func() {
		file_goods_info_v1_goods_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_info_v1_goods_info_proto_rawDesc), len(file_goods_info_v1_goods_info_proto_rawDesc)))
	})
	return file_goods_info_v1_goods_info_proto_rawDescData
}

var file_goods_info_v1_goods_info_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_goods_info_v1_goods_info_proto_goTypes = []any{
	(*GoodsInfoGetDetailReq)(nil), // 0: goods_info.v1.GoodsInfoGetDetailReq
	(*GoodsInfoGetDetailRes)(nil), // 1: goods_info.v1.GoodsInfoGetDetailRes
	(*GoodsInfoCreateReq)(nil),    // 2: goods_info.v1.GoodsInfoCreateReq
	(*GoodsInfoCreateRes)(nil),    // 3: goods_info.v1.GoodsInfoCreateRes
	(*GoodsInfoUpdateReq)(nil),    // 4: goods_info.v1.GoodsInfoUpdateReq
	(*GoodsInfoUpdateRes)(nil),    // 5: goods_info.v1.GoodsInfoUpdateRes
	(*GoodsInfoDeleteReq)(nil),    // 6: goods_info.v1.GoodsInfoDeleteReq
	(*GoodsInfoDeleteRes)(nil),    // 7: goods_info.v1.GoodsInfoDeleteRes
	(*GoodsInfoGetListReq)(nil),   // 8: goods_info.v1.GoodsInfoGetListReq
	(*GoodsInfoListResponse)(nil), // 9: goods_info.v1.GoodsInfoListResponse
	(*GoodsInfoGetListRes)(nil),   // 10: goods_info.v1.GoodsInfoGetListRes
	(*pbentity.GoodsInfo)(nil),    // 11: pbentity.GoodsInfo
}
var file_goods_info_v1_goods_info_proto_depIdxs = []int32{
	11, // 0: goods_info.v1.GoodsInfoGetDetailRes.data:type_name -> pbentity.GoodsInfo
	11, // 1: goods_info.v1.GoodsInfoListResponse.list:type_name -> pbentity.GoodsInfo
	9,  // 2: goods_info.v1.GoodsInfoGetListRes.data:type_name -> goods_info.v1.GoodsInfoListResponse
	8,  // 3: goods_info.v1.goods_info.GetList:input_type -> goods_info.v1.GoodsInfoGetListReq
	0,  // 4: goods_info.v1.goods_info.GetDetail:input_type -> goods_info.v1.GoodsInfoGetDetailReq
	2,  // 5: goods_info.v1.goods_info.Create:input_type -> goods_info.v1.GoodsInfoCreateReq
	4,  // 6: goods_info.v1.goods_info.Update:input_type -> goods_info.v1.GoodsInfoUpdateReq
	6,  // 7: goods_info.v1.goods_info.Delete:input_type -> goods_info.v1.GoodsInfoDeleteReq
	10, // 8: goods_info.v1.goods_info.GetList:output_type -> goods_info.v1.GoodsInfoGetListRes
	1,  // 9: goods_info.v1.goods_info.GetDetail:output_type -> goods_info.v1.GoodsInfoGetDetailRes
	3,  // 10: goods_info.v1.goods_info.Create:output_type -> goods_info.v1.GoodsInfoCreateRes
	5,  // 11: goods_info.v1.goods_info.Update:output_type -> goods_info.v1.GoodsInfoUpdateRes
	7,  // 12: goods_info.v1.goods_info.Delete:output_type -> goods_info.v1.GoodsInfoDeleteRes
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_goods_info_v1_goods_info_proto_init() }
func file_goods_info_v1_goods_info_proto_init() {
	if File_goods_info_v1_goods_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_info_v1_goods_info_proto_rawDesc), len(file_goods_info_v1_goods_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_info_v1_goods_info_proto_goTypes,
		DependencyIndexes: file_goods_info_v1_goods_info_proto_depIdxs,
		MessageInfos:      file_goods_info_v1_goods_info_proto_msgTypes,
	}.Build()
	File_goods_info_v1_goods_info_proto = out.File
	file_goods_info_v1_goods_info_proto_goTypes = nil
	file_goods_info_v1_goods_info_proto_depIdxs = nil
}
