// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/goods_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                         //
	Name             string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" dc:"商品名字"`                            // 商品名字
	PicUrl           string                 `protobuf:"bytes,3,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"主图"`                          // 主图
	Images           string                 `protobuf:"bytes,4,opt,name=Images,proto3" json:"Images,omitempty" dc:"支持单图,多图"`                     // 支持单图,多图
	Price            int32                  `protobuf:"varint,5,opt,name=Price,proto3" json:"Price,omitempty" dc:"价格(分)"`                        // 价格(分)
	Level1CategoryId int32                  `protobuf:"varint,6,opt,name=Level1CategoryId,proto3" json:"Level1CategoryId,omitempty" dc:"1级分类id"` // 1级分类id
	Level2CategoryId int32                  `protobuf:"varint,7,opt,name=Level2CategoryId,proto3" json:"Level2CategoryId,omitempty" dc:"2级分类id"` // 2级分类id
	Level3CategoryId int32                  `protobuf:"varint,8,opt,name=Level3CategoryId,proto3" json:"Level3CategoryId,omitempty" dc:"3级分类id"` // 3级分类id
	Brand            string                 `protobuf:"bytes,9,opt,name=Brand,proto3" json:"Brand,omitempty" dc:"品牌"`                            // 品牌
	Stock            int32                  `protobuf:"varint,10,opt,name=Stock,proto3" json:"Stock,omitempty" dc:"库存"`                          // 库存
	Sale             int32                  `protobuf:"varint,11,opt,name=Sale,proto3" json:"Sale,omitempty" dc:"销量"`                            // 销量
	Tags             string                 `protobuf:"bytes,12,opt,name=Tags,proto3" json:"Tags,omitempty" dc:"标签"`                             // 标签
	DetailInfo       string                 `protobuf:"bytes,13,opt,name=DetailInfo,proto3" json:"DetailInfo,omitempty" dc:"商品详情"`               // 商品详情
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                           //
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                           //
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`                           //
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	mi := &file_pbentity_goods_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_goods_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_goods_info_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfo) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *GoodsInfo) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *GoodsInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfo) GetLevel1CategoryId() int32 {
	if x != nil {
		return x.Level1CategoryId
	}
	return 0
}

func (x *GoodsInfo) GetLevel2CategoryId() int32 {
	if x != nil {
		return x.Level2CategoryId
	}
	return 0
}

func (x *GoodsInfo) GetLevel3CategoryId() int32 {
	if x != nil {
		return x.Level3CategoryId
	}
	return 0
}

func (x *GoodsInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GoodsInfo) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsInfo) GetSale() int32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsInfo) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GoodsInfo) GetDetailInfo() string {
	if x != nil {
		return x.DetailInfo
	}
	return ""
}

func (x *GoodsInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GoodsInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GoodsInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_goods_info_proto protoreflect.FileDescriptor

const file_pbentity_goods_info_proto_rawDesc = "" +
	"\n" +
	"\x19pbentity/goods_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x04\n" +
	"\tGoodsInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06PicUrl\x18\x03 \x01(\tR\x06PicUrl\x12\x16\n" +
	"\x06Images\x18\x04 \x01(\tR\x06Images\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x05R\x05Price\x12*\n" +
	"\x10Level1CategoryId\x18\x06 \x01(\x05R\x10Level1CategoryId\x12*\n" +
	"\x10Level2CategoryId\x18\a \x01(\x05R\x10Level2CategoryId\x12*\n" +
	"\x10Level3CategoryId\x18\b \x01(\x05R\x10Level3CategoryId\x12\x14\n" +
	"\x05Brand\x18\t \x01(\tR\x05Brand\x12\x14\n" +
	"\x05Stock\x18\n" +
	" \x01(\x05R\x05Stock\x12\x12\n" +
	"\x04Sale\x18\v \x01(\x05R\x04Sale\x12\x12\n" +
	"\x04Tags\x18\f \x01(\tR\x04Tags\x12\x1e\n" +
	"\n" +
	"DetailInfo\x18\r \x01(\tR\n" +
	"DetailInfo\x128\n" +
	"\tCreatedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tDeletedAt\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB Z\x1eservice/app/goods/api/pbentityb\x06proto3"

var (
	file_pbentity_goods_info_proto_rawDescOnce sync.Once
	file_pbentity_goods_info_proto_rawDescData []byte
)

func file_pbentity_goods_info_proto_rawDescGZIP() []byte {
	file_pbentity_goods_info_proto_rawDescOnce.Do(func() {
		file_pbentity_goods_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_goods_info_proto_rawDesc), len(file_pbentity_goods_info_proto_rawDesc)))
	})
	return file_pbentity_goods_info_proto_rawDescData
}

var file_pbentity_goods_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_goods_info_proto_goTypes = []any{
	(*GoodsInfo)(nil),             // 0: pbentity.GoodsInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_goods_info_proto_depIdxs = []int32{
	1, // 0: pbentity.GoodsInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.GoodsInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.GoodsInfo.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_goods_info_proto_init() }
func file_pbentity_goods_info_proto_init() {
	if File_pbentity_goods_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_goods_info_proto_rawDesc), len(file_pbentity_goods_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_goods_info_proto_goTypes,
		DependencyIndexes: file_pbentity_goods_info_proto_depIdxs,
		MessageInfos:      file_pbentity_goods_info_proto_msgTypes,
	}.Build()
	File_pbentity_goods_info_proto = out.File
	file_pbentity_goods_info_proto_goTypes = nil
	file_pbentity_goods_info_proto_depIdxs = nil
}
