// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/goods_images.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsImages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                //
	Url           string                 `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty" dc:"七牛云url"`                   // 七牛云url
	GoodsId       int32                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品ID"`            // 商品ID
	FileId        int32                  `protobuf:"varint,4,opt,name=FileId,proto3" json:"FileId,omitempty" dc:"文件ID（关联file_info）"` // 文件ID（关联file_info）
	Sort          int32                  `protobuf:"varint,5,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"排序"`                    // 排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsImages) Reset() {
	*x = GoodsImages{}
	mi := &file_pbentity_goods_images_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsImages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImages) ProtoMessage() {}

func (x *GoodsImages) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_goods_images_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImages.ProtoReflect.Descriptor instead.
func (*GoodsImages) Descriptor() ([]byte, []int) {
	return file_pbentity_goods_images_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsImages) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsImages) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GoodsImages) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsImages) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *GoodsImages) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

var File_pbentity_goods_images_proto protoreflect.FileDescriptor

const file_pbentity_goods_images_proto_rawDesc = "" +
	"\n" +
	"\x1bpbentity/goods_images.proto\x12\bpbentity\"u\n" +
	"\vGoodsImages\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x10\n" +
	"\x03Url\x18\x02 \x01(\tR\x03Url\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x05R\aGoodsId\x12\x16\n" +
	"\x06FileId\x18\x04 \x01(\x05R\x06FileId\x12\x12\n" +
	"\x04Sort\x18\x05 \x01(\x05R\x04SortB Z\x1eservice/app/goods/api/pbentityb\x06proto3"

var (
	file_pbentity_goods_images_proto_rawDescOnce sync.Once
	file_pbentity_goods_images_proto_rawDescData []byte
)

func file_pbentity_goods_images_proto_rawDescGZIP() []byte {
	file_pbentity_goods_images_proto_rawDescOnce.Do(func() {
		file_pbentity_goods_images_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_goods_images_proto_rawDesc), len(file_pbentity_goods_images_proto_rawDesc)))
	})
	return file_pbentity_goods_images_proto_rawDescData
}

var file_pbentity_goods_images_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_goods_images_proto_goTypes = []any{
	(*GoodsImages)(nil), // 0: pbentity.GoodsImages
}
var file_pbentity_goods_images_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbentity_goods_images_proto_init() }
func file_pbentity_goods_images_proto_init() {
	if File_pbentity_goods_images_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_goods_images_proto_rawDesc), len(file_pbentity_goods_images_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_goods_images_proto_goTypes,
		DependencyIndexes: file_pbentity_goods_images_proto_depIdxs,
		MessageInfos:      file_pbentity_goods_images_proto_msgTypes,
	}.Build()
	File_pbentity_goods_images_proto = out.File
	file_pbentity_goods_images_proto_goTypes = nil
	file_pbentity_goods_images_proto_depIdxs = nil
}
