// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: goods_images/v1/goods_images.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsImagesCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodId        uint32                 `protobuf:"varint,1,opt,name=GoodId,proto3" json:"GoodId,omitempty"`
	FileId        uint32                 `protobuf:"varint,2,opt,name=FileId,proto3" json:"FileId,omitempty"`
	Sort          uint32                 `protobuf:"varint,3,opt,name=Sort,proto3" json:"Sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsImagesCreateReq) Reset() {
	*x = GoodsImagesCreateReq{}
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsImagesCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesCreateReq) ProtoMessage() {}

func (x *GoodsImagesCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesCreateReq.ProtoReflect.Descriptor instead.
func (*GoodsImagesCreateReq) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsImagesCreateReq) GetGoodId() uint32 {
	if x != nil {
		return x.GoodId
	}
	return 0
}

func (x *GoodsImagesCreateReq) GetFileId() uint32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *GoodsImagesCreateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type GoodsImagesCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsImagesCreateRes) Reset() {
	*x = GoodsImagesCreateRes{}
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsImagesCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesCreateRes) ProtoMessage() {}

func (x *GoodsImagesCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesCreateRes.ProtoReflect.Descriptor instead.
func (*GoodsImagesCreateRes) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsImagesCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsImagesDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsImagesDeleteReq) Reset() {
	*x = GoodsImagesDeleteReq{}
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsImagesDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesDeleteReq) ProtoMessage() {}

func (x *GoodsImagesDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesDeleteReq.ProtoReflect.Descriptor instead.
func (*GoodsImagesDeleteReq) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsImagesDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsImagesDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsImagesDeleteRes) Reset() {
	*x = GoodsImagesDeleteRes{}
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsImagesDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesDeleteRes) ProtoMessage() {}

func (x *GoodsImagesDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesDeleteRes.ProtoReflect.Descriptor instead.
func (*GoodsImagesDeleteRes) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{3}
}

type GoodsImagesGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsImagesGetListReq) Reset() {
	*x = GoodsImagesGetListReq{}
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsImagesGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesGetListReq) ProtoMessage() {}

func (x *GoodsImagesGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesGetListReq.ProtoReflect.Descriptor instead.
func (*GoodsImagesGetListReq) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsImagesGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsImagesGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GoodsImagesListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	List          []*pbentity.GoodsImages `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsImagesListResponse) Reset() {
	*x = GoodsImagesListResponse{}
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsImagesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesListResponse) ProtoMessage() {}

func (x *GoodsImagesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesListResponse.ProtoReflect.Descriptor instead.
func (*GoodsImagesListResponse) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsImagesListResponse) GetList() []*pbentity.GoodsImages {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GoodsImagesListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsImagesListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GoodsImagesListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GoodsImagesGetListRes struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          *GoodsImagesListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsImagesGetListRes) Reset() {
	*x = GoodsImagesGetListRes{}
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsImagesGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesGetListRes) ProtoMessage() {}

func (x *GoodsImagesGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesGetListRes.ProtoReflect.Descriptor instead.
func (*GoodsImagesGetListRes) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsImagesGetListRes) GetData() *GoodsImagesListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_goods_images_v1_goods_images_proto protoreflect.FileDescriptor

const file_goods_images_v1_goods_images_proto_rawDesc = "" +
	"\n" +
	"\"goods_images/v1/goods_images.proto\x12\x0fgoods_images.v1\x1a\x1bpbentity/goods_images.proto\"Z\n" +
	"\x14GoodsImagesCreateReq\x12\x16\n" +
	"\x06GoodId\x18\x01 \x01(\rR\x06GoodId\x12\x16\n" +
	"\x06FileId\x18\x02 \x01(\rR\x06FileId\x12\x12\n" +
	"\x04Sort\x18\x03 \x01(\rR\x04Sort\"&\n" +
	"\x14GoodsImagesCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"&\n" +
	"\x14GoodsImagesDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x16\n" +
	"\x14GoodsImagesDeleteRes\"?\n" +
	"\x15GoodsImagesGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\x82\x01\n" +
	"\x17GoodsImagesListResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.pbentity.GoodsImagesR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"U\n" +
	"\x15GoodsImagesGetListRes\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.goods_images.v1.GoodsImagesListResponseR\x04data2\x9f\x02\n" +
	"\fgoods_images\x12[\n" +
	"\aGetList\x12&.goods_images.v1.GoodsImagesGetListReq\x1a&.goods_images.v1.GoodsImagesGetListRes\"\x00\x12X\n" +
	"\x06Create\x12%.goods_images.v1.GoodsImagesCreateReq\x1a%.goods_images.v1.GoodsImagesCreateRes\"\x00\x12X\n" +
	"\x06Delete\x12%.goods_images.v1.GoodsImagesDeleteReq\x1a%.goods_images.v1.GoodsImagesDeleteRes\"\x00B'Z%service/app/goods/api/goods_images/v1b\x06proto3"

var (
	file_goods_images_v1_goods_images_proto_rawDescOnce sync.Once
	file_goods_images_v1_goods_images_proto_rawDescData []byte
)

func file_goods_images_v1_goods_images_proto_rawDescGZIP() []byte {
	file_goods_images_v1_goods_images_proto_rawDescOnce.Do(func() {
		file_goods_images_v1_goods_images_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_images_v1_goods_images_proto_rawDesc), len(file_goods_images_v1_goods_images_proto_rawDesc)))
	})
	return file_goods_images_v1_goods_images_proto_rawDescData
}

var file_goods_images_v1_goods_images_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_goods_images_v1_goods_images_proto_goTypes = []any{
	(*GoodsImagesCreateReq)(nil),    // 0: goods_images.v1.GoodsImagesCreateReq
	(*GoodsImagesCreateRes)(nil),    // 1: goods_images.v1.GoodsImagesCreateRes
	(*GoodsImagesDeleteReq)(nil),    // 2: goods_images.v1.GoodsImagesDeleteReq
	(*GoodsImagesDeleteRes)(nil),    // 3: goods_images.v1.GoodsImagesDeleteRes
	(*GoodsImagesGetListReq)(nil),   // 4: goods_images.v1.GoodsImagesGetListReq
	(*GoodsImagesListResponse)(nil), // 5: goods_images.v1.GoodsImagesListResponse
	(*GoodsImagesGetListRes)(nil),   // 6: goods_images.v1.GoodsImagesGetListRes
	(*pbentity.GoodsImages)(nil),    // 7: pbentity.GoodsImages
}
var file_goods_images_v1_goods_images_proto_depIdxs = []int32{
	7, // 0: goods_images.v1.GoodsImagesListResponse.list:type_name -> pbentity.GoodsImages
	5, // 1: goods_images.v1.GoodsImagesGetListRes.data:type_name -> goods_images.v1.GoodsImagesListResponse
	4, // 2: goods_images.v1.goods_images.GetList:input_type -> goods_images.v1.GoodsImagesGetListReq
	0, // 3: goods_images.v1.goods_images.Create:input_type -> goods_images.v1.GoodsImagesCreateReq
	2, // 4: goods_images.v1.goods_images.Delete:input_type -> goods_images.v1.GoodsImagesDeleteReq
	6, // 5: goods_images.v1.goods_images.GetList:output_type -> goods_images.v1.GoodsImagesGetListRes
	1, // 6: goods_images.v1.goods_images.Create:output_type -> goods_images.v1.GoodsImagesCreateRes
	3, // 7: goods_images.v1.goods_images.Delete:output_type -> goods_images.v1.GoodsImagesDeleteRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_goods_images_v1_goods_images_proto_init() }
func file_goods_images_v1_goods_images_proto_init() {
	if File_goods_images_v1_goods_images_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_images_v1_goods_images_proto_rawDesc), len(file_goods_images_v1_goods_images_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_images_v1_goods_images_proto_goTypes,
		DependencyIndexes: file_goods_images_v1_goods_images_proto_depIdxs,
		MessageInfos:      file_goods_images_v1_goods_images_proto_msgTypes,
	}.Build()
	File_goods_images_v1_goods_images_proto = out.File
	file_goods_images_v1_goods_images_proto_goTypes = nil
	file_goods_images_v1_goods_images_proto_depIdxs = nil
}
