// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: refund_info/v1/refund_info.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/order/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefundInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OrderId       uint32                 `protobuf:"varint,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	GoodsId       uint32                 `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=Reason,proto3" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfoCreateReq) Reset() {
	*x = RefundInfoCreateReq{}
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoCreateReq) ProtoMessage() {}

func (x *RefundInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoCreateReq.ProtoReflect.Descriptor instead.
func (*RefundInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{0}
}

func (x *RefundInfoCreateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RefundInfoCreateReq) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RefundInfoCreateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *RefundInfoCreateReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfoCreateRes) Reset() {
	*x = RefundInfoCreateRes{}
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoCreateRes) ProtoMessage() {}

func (x *RefundInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoCreateRes.ProtoReflect.Descriptor instead.
func (*RefundInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{1}
}

func (x *RefundInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RefundInfoGetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfoGetDetailReq) Reset() {
	*x = RefundInfoGetDetailReq{}
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfoGetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoGetDetailReq) ProtoMessage() {}

func (x *RefundInfoGetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoGetDetailReq.ProtoReflect.Descriptor instead.
func (*RefundInfoGetDetailReq) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{2}
}

func (x *RefundInfoGetDetailReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RefundInfoGetDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *pbentity.RefundInfo   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfoGetDetailRes) Reset() {
	*x = RefundInfoGetDetailRes{}
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfoGetDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoGetDetailRes) ProtoMessage() {}

func (x *RefundInfoGetDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoGetDetailRes.ProtoReflect.Descriptor instead.
func (*RefundInfoGetDetailRes) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{3}
}

func (x *RefundInfoGetDetailRes) GetData() *pbentity.RefundInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type RefundInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfoGetListReq) Reset() {
	*x = RefundInfoGetListReq{}
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoGetListReq) ProtoMessage() {}

func (x *RefundInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoGetListReq.ProtoReflect.Descriptor instead.
func (*RefundInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{4}
}

func (x *RefundInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RefundInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RefundInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.RefundInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfoListResponse) Reset() {
	*x = RefundInfoListResponse{}
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoListResponse) ProtoMessage() {}

func (x *RefundInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoListResponse.ProtoReflect.Descriptor instead.
func (*RefundInfoListResponse) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{5}
}

func (x *RefundInfoListResponse) GetList() []*pbentity.RefundInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RefundInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RefundInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RefundInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RefundInfoGetListRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *RefundInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfoGetListRes) Reset() {
	*x = RefundInfoGetListRes{}
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoGetListRes) ProtoMessage() {}

func (x *RefundInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoGetListRes.ProtoReflect.Descriptor instead.
func (*RefundInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{6}
}

func (x *RefundInfoGetListRes) GetData() *RefundInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_refund_info_v1_refund_info_proto protoreflect.FileDescriptor

const file_refund_info_v1_refund_info_proto_rawDesc = "" +
	"\n" +
	" refund_info/v1/refund_info.proto\x12\x0erefund_info.v1\x1a\x1apbentity/refund_info.proto\"y\n" +
	"\x13RefundInfoCreateReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\rR\x06UserId\x12\x18\n" +
	"\aOrderId\x18\x02 \x01(\rR\aOrderId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\rR\aGoodsId\x12\x16\n" +
	"\x06Reason\x18\x04 \x01(\tR\x06Reason\"%\n" +
	"\x13RefundInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"(\n" +
	"\x16RefundInfoGetDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"B\n" +
	"\x16RefundInfoGetDetailRes\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.pbentity.RefundInfoR\x04data\">\n" +
	"\x14RefundInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\x80\x01\n" +
	"\x16RefundInfoListResponse\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.pbentity.RefundInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"R\n" +
	"\x14RefundInfoGetListRes\x12:\n" +
	"\x04data\x18\x01 \x01(\v2&.refund_info.v1.RefundInfoListResponseR\x04data2\x9b\x02\n" +
	"\vrefund_info\x12W\n" +
	"\aGetList\x12$.refund_info.v1.RefundInfoGetListReq\x1a$.refund_info.v1.RefundInfoGetListRes\"\x00\x12]\n" +
	"\tGetDetail\x12&.refund_info.v1.RefundInfoGetDetailReq\x1a&.refund_info.v1.RefundInfoGetDetailRes\"\x00\x12T\n" +
	"\x06Create\x12#.refund_info.v1.RefundInfoCreateReq\x1a#.refund_info.v1.RefundInfoCreateRes\"\x00B&Z$service/app/order/api/refund_info/v1b\x06proto3"

var (
	file_refund_info_v1_refund_info_proto_rawDescOnce sync.Once
	file_refund_info_v1_refund_info_proto_rawDescData []byte
)

func file_refund_info_v1_refund_info_proto_rawDescGZIP() []byte {
	file_refund_info_v1_refund_info_proto_rawDescOnce.Do(func() {
		file_refund_info_v1_refund_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_refund_info_v1_refund_info_proto_rawDesc), len(file_refund_info_v1_refund_info_proto_rawDesc)))
	})
	return file_refund_info_v1_refund_info_proto_rawDescData
}

var file_refund_info_v1_refund_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_refund_info_v1_refund_info_proto_goTypes = []any{
	(*RefundInfoCreateReq)(nil),    // 0: refund_info.v1.RefundInfoCreateReq
	(*RefundInfoCreateRes)(nil),    // 1: refund_info.v1.RefundInfoCreateRes
	(*RefundInfoGetDetailReq)(nil), // 2: refund_info.v1.RefundInfoGetDetailReq
	(*RefundInfoGetDetailRes)(nil), // 3: refund_info.v1.RefundInfoGetDetailRes
	(*RefundInfoGetListReq)(nil),   // 4: refund_info.v1.RefundInfoGetListReq
	(*RefundInfoListResponse)(nil), // 5: refund_info.v1.RefundInfoListResponse
	(*RefundInfoGetListRes)(nil),   // 6: refund_info.v1.RefundInfoGetListRes
	(*pbentity.RefundInfo)(nil),    // 7: pbentity.RefundInfo
}
var file_refund_info_v1_refund_info_proto_depIdxs = []int32{
	7, // 0: refund_info.v1.RefundInfoGetDetailRes.data:type_name -> pbentity.RefundInfo
	7, // 1: refund_info.v1.RefundInfoListResponse.list:type_name -> pbentity.RefundInfo
	5, // 2: refund_info.v1.RefundInfoGetListRes.data:type_name -> refund_info.v1.RefundInfoListResponse
	4, // 3: refund_info.v1.refund_info.GetList:input_type -> refund_info.v1.RefundInfoGetListReq
	2, // 4: refund_info.v1.refund_info.GetDetail:input_type -> refund_info.v1.RefundInfoGetDetailReq
	0, // 5: refund_info.v1.refund_info.Create:input_type -> refund_info.v1.RefundInfoCreateReq
	6, // 6: refund_info.v1.refund_info.GetList:output_type -> refund_info.v1.RefundInfoGetListRes
	3, // 7: refund_info.v1.refund_info.GetDetail:output_type -> refund_info.v1.RefundInfoGetDetailRes
	1, // 8: refund_info.v1.refund_info.Create:output_type -> refund_info.v1.RefundInfoCreateRes
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_refund_info_v1_refund_info_proto_init() }
func file_refund_info_v1_refund_info_proto_init() {
	if File_refund_info_v1_refund_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_refund_info_v1_refund_info_proto_rawDesc), len(file_refund_info_v1_refund_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_refund_info_v1_refund_info_proto_goTypes,
		DependencyIndexes: file_refund_info_v1_refund_info_proto_depIdxs,
		MessageInfos:      file_refund_info_v1_refund_info_proto_msgTypes,
	}.Build()
	File_refund_info_v1_refund_info_proto = out.File
	file_refund_info_v1_refund_info_proto_goTypes = nil
	file_refund_info_v1_refund_info_proto_depIdxs = nil
}
