// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: admin_info/v1/admin_info.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminInfo_Login_FullMethodName    = "/admin_info.v1.AdminInfo/Login"
	AdminInfo_Register_FullMethodName = "/admin_info.v1.AdminInfo/Register"
)

// AdminInfoClient is the client API for AdminInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminInfoClient interface {
	Login(ctx context.Context, in *AdminInfoLoginReq, opts ...grpc.CallOption) (*AdminInfoLoginRes, error)
	Register(ctx context.Context, in *AdminInfoRegisterReq, opts ...grpc.CallOption) (*AdminInfoRegisterRes, error)
}

type adminInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminInfoClient(cc grpc.ClientConnInterface) AdminInfoClient {
	return &adminInfoClient{cc}
}

func (c *adminInfoClient) Login(ctx context.Context, in *AdminInfoLoginReq, opts ...grpc.CallOption) (*AdminInfoLoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminInfoLoginRes)
	err := c.cc.Invoke(ctx, AdminInfo_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminInfoClient) Register(ctx context.Context, in *AdminInfoRegisterReq, opts ...grpc.CallOption) (*AdminInfoRegisterRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminInfoRegisterRes)
	err := c.cc.Invoke(ctx, AdminInfo_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminInfoServer is the server API for AdminInfo service.
// All implementations must embed UnimplementedAdminInfoServer
// for forward compatibility.
type AdminInfoServer interface {
	Login(context.Context, *AdminInfoLoginReq) (*AdminInfoLoginRes, error)
	Register(context.Context, *AdminInfoRegisterReq) (*AdminInfoRegisterRes, error)
	mustEmbedUnimplementedAdminInfoServer()
}

// UnimplementedAdminInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminInfoServer struct{}

func (UnimplementedAdminInfoServer) Login(context.Context, *AdminInfoLoginReq) (*AdminInfoLoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAdminInfoServer) Register(context.Context, *AdminInfoRegisterReq) (*AdminInfoRegisterRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAdminInfoServer) mustEmbedUnimplementedAdminInfoServer() {}
func (UnimplementedAdminInfoServer) testEmbeddedByValue()                   {}

// UnsafeAdminInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminInfoServer will
// result in compilation errors.
type UnsafeAdminInfoServer interface {
	mustEmbedUnimplementedAdminInfoServer()
}

func RegisterAdminInfoServer(s grpc.ServiceRegistrar, srv AdminInfoServer) {
	// If the following call pancis, it indicates UnimplementedAdminInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminInfo_ServiceDesc, srv)
}

func _AdminInfo_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminInfoLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminInfoServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminInfo_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminInfoServer).Login(ctx, req.(*AdminInfoLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminInfo_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminInfoRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminInfoServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminInfo_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminInfoServer).Register(ctx, req.(*AdminInfoRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminInfo_ServiceDesc is the grpc.ServiceDesc for AdminInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_info.v1.AdminInfo",
	HandlerType: (*AdminInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AdminInfo_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AdminInfo_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_info/v1/admin_info.proto",
}
