// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: admin_info/v1/admin_info.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminInfoLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfoLoginReq) Reset() {
	*x = AdminInfoLoginReq{}
	mi := &file_admin_info_v1_admin_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfoLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfoLoginReq) ProtoMessage() {}

func (x *AdminInfoLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_info_v1_admin_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfoLoginReq.ProtoReflect.Descriptor instead.
func (*AdminInfoLoginReq) Descriptor() ([]byte, []int) {
	return file_admin_info_v1_admin_info_proto_rawDescGZIP(), []int{0}
}

func (x *AdminInfoLoginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminInfoLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminInfoLoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expire        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfoLoginRes) Reset() {
	*x = AdminInfoLoginRes{}
	mi := &file_admin_info_v1_admin_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfoLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfoLoginRes) ProtoMessage() {}

func (x *AdminInfoLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_admin_info_v1_admin_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfoLoginRes.ProtoReflect.Descriptor instead.
func (*AdminInfoLoginRes) Descriptor() ([]byte, []int) {
	return file_admin_info_v1_admin_info_proto_rawDescGZIP(), []int{1}
}

func (x *AdminInfoLoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminInfoLoginRes) GetExpire() *timestamppb.Timestamp {
	if x != nil {
		return x.Expire
	}
	return nil
}

type AdminInfoRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfoRegisterReq) Reset() {
	*x = AdminInfoRegisterReq{}
	mi := &file_admin_info_v1_admin_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfoRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfoRegisterReq) ProtoMessage() {}

func (x *AdminInfoRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_info_v1_admin_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfoRegisterReq.ProtoReflect.Descriptor instead.
func (*AdminInfoRegisterReq) Descriptor() ([]byte, []int) {
	return file_admin_info_v1_admin_info_proto_rawDescGZIP(), []int{2}
}

func (x *AdminInfoRegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminInfoRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminInfoRegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoleIds       string                 `protobuf:"bytes,3,opt,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	IsAdmin       uint32                 `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfoRegisterRes) Reset() {
	*x = AdminInfoRegisterRes{}
	mi := &file_admin_info_v1_admin_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfoRegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfoRegisterRes) ProtoMessage() {}

func (x *AdminInfoRegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_admin_info_v1_admin_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfoRegisterRes.ProtoReflect.Descriptor instead.
func (*AdminInfoRegisterRes) Descriptor() ([]byte, []int) {
	return file_admin_info_v1_admin_info_proto_rawDescGZIP(), []int{3}
}

func (x *AdminInfoRegisterRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminInfoRegisterRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminInfoRegisterRes) GetRoleIds() string {
	if x != nil {
		return x.RoleIds
	}
	return ""
}

func (x *AdminInfoRegisterRes) GetIsAdmin() uint32 {
	if x != nil {
		return x.IsAdmin
	}
	return 0
}

func (x *AdminInfoRegisterRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_admin_info_v1_admin_info_proto protoreflect.FileDescriptor

const file_admin_info_v1_admin_info_proto_rawDesc = "" +
	"\n" +
	"\x1eadmin_info/v1/admin_info.proto\x12\radmin_info.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x11AdminInfoLoginReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"]\n" +
	"\x11AdminInfoLoginRes\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x122\n" +
	"\x06expire\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06expire\"F\n" +
	"\x14AdminInfoRegisterReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xab\x01\n" +
	"\x14AdminInfoRegisterRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\brole_ids\x18\x03 \x01(\tR\aroleIds\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\rR\aisAdmin\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xb2\x01\n" +
	"\tAdminInfo\x12M\n" +
	"\x05Login\x12 .admin_info.v1.AdminInfoLoginReq\x1a .admin_info.v1.AdminInfoLoginRes\"\x00\x12V\n" +
	"\bRegister\x12#.admin_info.v1.AdminInfoRegisterReq\x1a#.admin_info.v1.AdminInfoRegisterRes\"\x00BBZ@shop-goframe-micro-service-refacotor/app/admin/api/admin_info/v1b\x06proto3"

var (
	file_admin_info_v1_admin_info_proto_rawDescOnce sync.Once
	file_admin_info_v1_admin_info_proto_rawDescData []byte
)

func file_admin_info_v1_admin_info_proto_rawDescGZIP() []byte {
	file_admin_info_v1_admin_info_proto_rawDescOnce.Do(func() {
		file_admin_info_v1_admin_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_info_v1_admin_info_proto_rawDesc), len(file_admin_info_v1_admin_info_proto_rawDesc)))
	})
	return file_admin_info_v1_admin_info_proto_rawDescData
}

var file_admin_info_v1_admin_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_info_v1_admin_info_proto_goTypes = []any{
	(*AdminInfoLoginReq)(nil),     // 0: admin_info.v1.AdminInfoLoginReq
	(*AdminInfoLoginRes)(nil),     // 1: admin_info.v1.AdminInfoLoginRes
	(*AdminInfoRegisterReq)(nil),  // 2: admin_info.v1.AdminInfoRegisterReq
	(*AdminInfoRegisterRes)(nil),  // 3: admin_info.v1.AdminInfoRegisterRes
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_admin_info_v1_admin_info_proto_depIdxs = []int32{
	4, // 0: admin_info.v1.AdminInfoLoginRes.expire:type_name -> google.protobuf.Timestamp
	4, // 1: admin_info.v1.AdminInfoRegisterRes.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: admin_info.v1.AdminInfo.Login:input_type -> admin_info.v1.AdminInfoLoginReq
	2, // 3: admin_info.v1.AdminInfo.Register:input_type -> admin_info.v1.AdminInfoRegisterReq
	1, // 4: admin_info.v1.AdminInfo.Login:output_type -> admin_info.v1.AdminInfoLoginRes
	3, // 5: admin_info.v1.AdminInfo.Register:output_type -> admin_info.v1.AdminInfoRegisterRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_admin_info_v1_admin_info_proto_init() }
func file_admin_info_v1_admin_info_proto_init() {
	if File_admin_info_v1_admin_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_info_v1_admin_info_proto_rawDesc), len(file_admin_info_v1_admin_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_info_v1_admin_info_proto_goTypes,
		DependencyIndexes: file_admin_info_v1_admin_info_proto_depIdxs,
		MessageInfos:      file_admin_info_v1_admin_info_proto_msgTypes,
	}.Build()
	File_admin_info_v1_admin_info_proto = out.File
	file_admin_info_v1_admin_info_proto_goTypes = nil
	file_admin_info_v1_admin_info_proto_depIdxs = nil
}
