// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: praise_info/v1/praise_info.proto

package v1

import (
	reflect "reflect"
	pbentity "service/app/interaction/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PraiseInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint32                 `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoCreateReq) Reset() {
	*x = PraiseInfoCreateReq{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoCreateReq) ProtoMessage() {}

func (x *PraiseInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoCreateReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{0}
}

func (x *PraiseInfoCreateReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *PraiseInfoCreateReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type PraiseInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoCreateRes) Reset() {
	*x = PraiseInfoCreateRes{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoCreateRes) ProtoMessage() {}

func (x *PraiseInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoCreateRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{1}
}

func (x *PraiseInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PraiseInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	ObjectId      uint32                 `protobuf:"varint,3,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoDeleteReq) Reset() {
	*x = PraiseInfoDeleteReq{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoDeleteReq) ProtoMessage() {}

func (x *PraiseInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{2}
}

func (x *PraiseInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PraiseInfoDeleteReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PraiseInfoDeleteReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type PraiseInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoDeleteRes) Reset() {
	*x = PraiseInfoDeleteRes{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoDeleteRes) ProtoMessage() {}

func (x *PraiseInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{3}
}

func (x *PraiseInfoDeleteRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PraiseInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoGetListReq) Reset() {
	*x = PraiseInfoGetListReq{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoGetListReq) ProtoMessage() {}

func (x *PraiseInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoGetListReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{4}
}

func (x *PraiseInfoGetListReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PraiseInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PraiseInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PraiseInfoGetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.PraiseInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoGetListResponse) Reset() {
	*x = PraiseInfoGetListResponse{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoGetListResponse) ProtoMessage() {}

func (x *PraiseInfoGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoGetListResponse.ProtoReflect.Descriptor instead.
func (*PraiseInfoGetListResponse) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{5}
}

func (x *PraiseInfoGetListResponse) GetList() []*pbentity.PraiseInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PraiseInfoGetListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PraiseInfoGetListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PraiseInfoGetListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PraiseInfoGetListRes struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          *PraiseInfoGetListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoGetListRes) Reset() {
	*x = PraiseInfoGetListRes{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoGetListRes) ProtoMessage() {}

func (x *PraiseInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoGetListRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{6}
}

func (x *PraiseInfoGetListRes) GetData() *PraiseInfoGetListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_praise_info_v1_praise_info_proto protoreflect.FileDescriptor

const file_praise_info_v1_praise_info_proto_rawDesc = "" +
	"\n" +
	" praise_info/v1/praise_info.proto\x12\x0epraise_info.v1\x1a\x1apbentity/praise_info.proto\"E\n" +
	"\x13PraiseInfoCreateReq\x12\x1a\n" +
	"\bObjectId\x18\x01 \x01(\rR\bObjectId\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\rR\x04Type\"%\n" +
	"\x13PraiseInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"U\n" +
	"\x13PraiseInfoDeleteReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\rR\x04Type\x12\x1a\n" +
	"\bObjectId\x18\x03 \x01(\rR\bObjectId\"%\n" +
	"\x13PraiseInfoDeleteRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"R\n" +
	"\x14PraiseInfoGetListReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"\x83\x01\n" +
	"\x19PraiseInfoGetListResponse\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.pbentity.PraiseInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"U\n" +
	"\x14PraiseInfoGetListRes\x12=\n" +
	"\x04data\x18\x01 \x01(\v2).praise_info.v1.PraiseInfoGetListResponseR\x04data2\x92\x02\n" +
	"\vpraise_info\x12W\n" +
	"\aGetList\x12$.praise_info.v1.PraiseInfoGetListReq\x1a$.praise_info.v1.PraiseInfoGetListRes\"\x00\x12T\n" +
	"\x06Create\x12#.praise_info.v1.PraiseInfoCreateReq\x1a#.praise_info.v1.PraiseInfoCreateRes\"\x00\x12T\n" +
	"\x06Delete\x12#.praise_info.v1.PraiseInfoDeleteReq\x1a#.praise_info.v1.PraiseInfoDeleteRes\"\x00B,Z*service/app/interaction/api/praise_info/v1b\x06proto3"

var (
	file_praise_info_v1_praise_info_proto_rawDescOnce sync.Once
	file_praise_info_v1_praise_info_proto_rawDescData []byte
)

func file_praise_info_v1_praise_info_proto_rawDescGZIP() []byte {
	file_praise_info_v1_praise_info_proto_rawDescOnce.Do(func() {
		file_praise_info_v1_praise_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_praise_info_v1_praise_info_proto_rawDesc), len(file_praise_info_v1_praise_info_proto_rawDesc)))
	})
	return file_praise_info_v1_praise_info_proto_rawDescData
}

var file_praise_info_v1_praise_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_praise_info_v1_praise_info_proto_goTypes = []any{
	(*PraiseInfoCreateReq)(nil),       // 0: praise_info.v1.PraiseInfoCreateReq
	(*PraiseInfoCreateRes)(nil),       // 1: praise_info.v1.PraiseInfoCreateRes
	(*PraiseInfoDeleteReq)(nil),       // 2: praise_info.v1.PraiseInfoDeleteReq
	(*PraiseInfoDeleteRes)(nil),       // 3: praise_info.v1.PraiseInfoDeleteRes
	(*PraiseInfoGetListReq)(nil),      // 4: praise_info.v1.PraiseInfoGetListReq
	(*PraiseInfoGetListResponse)(nil), // 5: praise_info.v1.PraiseInfoGetListResponse
	(*PraiseInfoGetListRes)(nil),      // 6: praise_info.v1.PraiseInfoGetListRes
	(*pbentity.PraiseInfo)(nil),       // 7: pbentity.PraiseInfo
}
var file_praise_info_v1_praise_info_proto_depIdxs = []int32{
	7, // 0: praise_info.v1.PraiseInfoGetListResponse.list:type_name -> pbentity.PraiseInfo
	5, // 1: praise_info.v1.PraiseInfoGetListRes.data:type_name -> praise_info.v1.PraiseInfoGetListResponse
	4, // 2: praise_info.v1.praise_info.GetList:input_type -> praise_info.v1.PraiseInfoGetListReq
	0, // 3: praise_info.v1.praise_info.Create:input_type -> praise_info.v1.PraiseInfoCreateReq
	2, // 4: praise_info.v1.praise_info.Delete:input_type -> praise_info.v1.PraiseInfoDeleteReq
	6, // 5: praise_info.v1.praise_info.GetList:output_type -> praise_info.v1.PraiseInfoGetListRes
	1, // 6: praise_info.v1.praise_info.Create:output_type -> praise_info.v1.PraiseInfoCreateRes
	3, // 7: praise_info.v1.praise_info.Delete:output_type -> praise_info.v1.PraiseInfoDeleteRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_praise_info_v1_praise_info_proto_init() }
func file_praise_info_v1_praise_info_proto_init() {
	if File_praise_info_v1_praise_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_praise_info_v1_praise_info_proto_rawDesc), len(file_praise_info_v1_praise_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_praise_info_v1_praise_info_proto_goTypes,
		DependencyIndexes: file_praise_info_v1_praise_info_proto_depIdxs,
		MessageInfos:      file_praise_info_v1_praise_info_proto_msgTypes,
	}.Build()
	File_praise_info_v1_praise_info_proto = out.File
	file_praise_info_v1_praise_info_proto_goTypes = nil
	file_praise_info_v1_praise_info_proto_depIdxs = nil
}
